### ISSUE TITLE
Adapt Foreign Arithmetic APIs to ffmul changes

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#1036]
The foreign field multiplication gate is being updated to be more secure. This issue represents the work to adapt the SnarkyJS implementation accordingly.

**Comment by nicc** [comment]
Blocked by [this PR](https://github.com/MinaProtocol/mina/pull/13664)

**Comment by nicc** [comment]
Blocks https://github.com/o1-labs/snarkyjs/pull/985 and https://github.com/o1-labs/snarkyjs/pull/1007

**Comment by garwalsh** [comment]
Done but waiting for review, Joseph and Anais

**Comment by mitschabaude** [comment]
this is mostly done in a branch, but will be rewritten. closing because the upcoming work is better covered by other issues
