### ISSUE TITLE
Using lighweight local mina network Docker image in the standard zkApps development workflow

### ISSUE THREAD

**Issue by nicc** [o1-labs/o1js#1037]
This epic tracks progress toward our community using a lightweight network in a Docker image during local zkApp development.

As part of delivering this we will also dogfood this image on CI so note that some issues will not be overtly community-facing.

**Comment by barriebyron** [comment]
- improved Docker Hub image text to @Serhii Shymkiv for review https://hackmd.io/TPlu6kYUR4WQD5IGRWUsDw?view 
- updated how to test a zkApp with a section and link to the lightweight mina Docker Hub

**Comment by MartinMinkov** [comment]
Should this be closed now?
