### ISSUE TITLE
Generalize non-foreign Field in an ergonomic manner

### ISSUE THREAD

**Issue by bkase** [o1-labs/o1js#1053]
Right now `Field` is hardcoded to the Pasta base field; there should be a mechanism for swapping it for something else.

Consider using generics, runtime dependency injection. Note that there are some library code that can be generalized over the Field and some that can't, so we'll need to support that.

PRD and RFC needed.

**Comment by stevenpack** [comment]
@bkase re: 

> there should be a mechanism for swapping it for something else.

Why should there be? What is blocked by this? What would be enabled by it? What would be an example replacement?
