### ISSUE TITLE
Dynamic Array Access in SnarkyJS

### ISSUE THREAD

**Issue by shreyas-londhe** [o1-labs/o1js#1062]
Hi! I was looking for a way to do array access using `Field` elements, but could not find any documentation for it. I would be more than happy to implement a naive `quin_selector` -- [circom implementation](https://github.com/darkforest-eth/circuits/blob/master/perlin/QuinSelector.circom) for the time being, but I believe that's not a long term solution.

Any help is much appreciated!

**Comment by shryasss** [comment]
This is the naive implementation:
```
/**
 * Selects an element from an array based on an index.
 * @param arr The array to select from.
 * @param index The index of the element to select.
 * @returns The selected element.
 */
export const quinSelector = (arr: Field[], index: Field) => {
  index.lessThan(Field(arr.length)).assertTrue();

  let out = [];
  for (let i = 0; i < arr.length; i++) {
    out.push(arr[i].mul(index.equals(Field(i)).toField()));
  }

  let res = Field(0);
  for (let i = 0; i < arr.length; i++) {
    res = res.add(out[i]);
  }

  return res;
};
```

**Comment by mitschabaude** [comment]
Yep, I have used the same pattern. I don't think there's anything better without lookup based array access (which will come to snarkyjs within the next months)

**Comment by Trivo25** [comment]
closing in favor of #1086
