### ISSUE TITLE
circuit compilation fail by some errors

### ISSUE THREAD

**Issue by coldstar1993** [o1-labs/o1js#1088]
Background:
  My Machine: 36c, 128GB.

  My two circuits' size are not small. When I compile them (with `node --experimental-wasm-memory64` ), got the errors respectively as blow:

**`TypeError:The encoded data was not valid for encoding utf-8`**
![image](https://github.com/o1-labs/snarkyjs/assets/92623877/5fcd6a5f-024b-46a2-9d25-faab341f7850)

**`Errors: curve point must not be the point at infinity`**
![image](https://github.com/o1-labs/snarkyjs/assets/92623877/d099ae4c-c264-49f0-bcf5-2cef5cdb9979)
  
 These error seems NOT from that the circuit size exceeds the upper limit (though, might be close).
  
  Later, I tried to simplify the circuit by reducing some constraints or operations, like lower merkle-tree heights, rid some constraints, etc. Then they could smoothly be compiled.
  
  My question: if my circuit size does not exceed, why I compiled them with `wasm-memory64`, but still got these errors?
  Furthermore, does snarkyJS support wasm64 currently??

**Comment by mitschabaude** [comment]
the wasm code compiled from kimchi is definitely not using 64-bit memory, so I wouldn't expect the flag `--experimental-wasm-memory64` to have an effect

**Comment by coldstar1993** [comment]
We team are on a L2Rollup product, the circuits' dependency relationship: `zkPragramC <- zkPragramB <- RollupContractA`， each one is **small** circuit that is **NOT** close to the preset upper limit of constraints amount.  

I could compile `zkPragramC` and `zkPragramB` as sequence smoothly. But after that,  the former two circuits' compilation result has already been occupying really much memory(exactly,  _addressing spaces_), and not enough memory(_addressing spaces_) left for later compilation of `RollupContractA`, as well as further proving progresses.

What we could do currently is to reduce the merkle-tree height to a really small value, to decrease memory( _addressing spaces_) occupy to make all circuits compiled and run. But this limit our product really much.

Although our machine memory is 128GB, but due to the wasm code compiled from kimchi is using 32-bit memory, much of _machine memory_ left could not be made usage of for circuits.
So I wonder if snarkyJS will support wasm64 in soon future?

**Comment by coldstar1993** [comment]
Besides, how about the progress about 'Expose side loaded verification key to snarkyjs' at  [#673](https://github.com/o1-labs/snarkyjs/issues/673) ??  It would help much!!

**Comment by mitschabaude** [comment]
> Besides, how about the progress about 'Expose side loaded verification key to snarkyjs' at [#673](https://github.com/o1-labs/snarkyjs/issues/673) ?? It would help much!!

Unfortunately we haven't planned to do this in the next 2-4 weeks
