### ISSUE TITLE
Typescript errors on build

### ISSUE THREAD

**Issue by directcuteo** [o1-labs/o1js#1121]
I cannot build the freshly cloned **o1js**. There are a lot of errors in the Typescript code

![image](https://github.com/o1-labs/o1js/assets/37619567/cfd6be48-a5f7-4249-8ff4-18194a457355)

**Comment by mitschabaude** [comment]
Hey @directcuteo you need to pull the [o1js-bindings](https://github.com/o1-labs/o1js-bindings) submodule where some of the dependencies are contained
