### ISSUE TITLE
method decorator doesn't work in browser

### ISSUE THREAD

**Issue by directcuteo** [o1-labs/o1js#1126]
Whenever I import method decorator in my browser based application, I am receiving the following error.
![Screenshot 2023-09-20 at 14 11 54](https://github.com/o1-labs/o1js/assets/37619567/1d19d03b-1640-4da6-b016-0dcb474dff66)

This is the entire code:
```
import { Field, method, SmartContract } from "o1js";

class Square extends SmartContract {
  @method update(square: Field) {
  }
}
```

This code doesn't produce the error:

```
import { Field, method, SmartContract } from "o1js";

class Square extends SmartContract {
  // @method update(square: Field) {
  // }
}
```

How can I overcome this issue?

**Comment by directcuteo** [comment]
### Update:
Location of the error:
https://github.com/o1-labs/o1js/blob/0bc79959ecb54a49ffadee0f8c7143d4c52b4b9c/src/lib/proof_system.ts#L396
It seems that the error is coming because this code is "broken".
https://github.com/o1-labs/o1js/blob/0bc79959ecb54a49ffadee0f8c7143d4c52b4b9c/src/lib/zkapp.ts#L98

I changed the code to 
``` 
let paramTypes: Provable<any>[] = Reflect.getMetadata(
  'design:paramtypes',
  target,
  methodName
) || [];
```

And now it seems to work.

**Comment by mitschabaude** [comment]
The proper code change would be to throw the same error you observed but make the error message more informative

**Comment by mitschabaude** [comment]
@directcuteo you can get around decorators not working by using declareMethods / declareState instead of method / state decorators

**Comment by directcuteo** [comment]
@mitschabaude That is great piece of info!

So I added these 2 functions instead of the decorators. Now when the line `zkAppInstance.deploy()` is executed, I receive the following error:

![Screenshot 2023-09-21 at 11 51 30](https://github.com/o1-labs/o1js/assets/37619567/d474b855-d0aa-41d5-8a8b-aaece9f4b3f7)


### Here is the code 

```
      class Square extends SmartContract {
        num: State<Field>;

        constructor(num: PublicKey) {
          super(num);
          this.num = State();
        }

        override init() {
          super.init();
          this.num.set(Field(3));
        }

        update(square: Field) {
          const currentState = this.num.get();
          this.num.assertEquals(currentState);
          square.assertEquals(currentState.mul(currentState));
          this.num.set(square);
        }
      }

      declareMethods(Square, { update: [Field] });
      declareState(Square, { num: Field });

      await isReady;

      console.log("o1js loaded");

      const useProof = false;

      const Local = Mina.LocalBlockchain({ proofsEnabled: useProof });
      Mina.setActiveInstance(Local);
      const { privateKey: deployerKey, publicKey: deployerAccount } = Local.testAccounts[0];
      const { privateKey: senderKey, publicKey: senderAccount } = Local.testAccounts[1];

// ----------------------------------------------------

// Create a public/private key pair. The public key is your address and where you deploy the zkApp to
      const zkAppPrivateKey = PrivateKey.random();
      const zkAppAddress = zkAppPrivateKey.toPublicKey();

// create an instance of Square - and deploy it to zkAppAddress
      const zkAppInstance = new Square(zkAppAddress);
      console.log('initiated Square');
      const deployTxn = await Mina.transaction(deployerAccount, () => {
        AccountUpdate.fundNewAccount(deployerAccount);
        zkAppInstance.deploy();
      });
      console.log('signing');
      await deployTxn.sign([deployerKey, zkAppPrivateKey]).send();
      console.log('signed');
// get the initial state of Square after deployment
      const num0 = zkAppInstance.num.get();
      console.log("state after init:", num0.toString());
```

Now sure what is wrong since I followed the docs

**Comment by mitschabaude** [comment]
I think this TS config option might be what you need, I vaguely recall it being related: https://github.com/o1-labs/o1js/blob/bb9cf00d6dbf74710690d5a2655e6205b05f9454/tsconfig.json#L15
