### ISSUE TITLE
Port Keccak (SHA3) gadget to TypeScript

### ISSUE THREAD

**Issue by nicc** [o1-labs/o1js#1146]
partly depends on interfaces to #1138 #1140 #1141 #1139 #1148

**Comment by Trivo25** [comment]
cc @jackryanservia to pick this up. if not, let me know

**Comment by barriebyron** [comment]
Docs need to land with these code updates for Keccak 
Docs issue https://app.zenhub.com/workspaces/zkapps-product-eng-6130fedb3b0fc600123d8796/issues/gh/o1-labs/docs2/741
