### ISSUE TITLE
Exercise more APIs during the live tests against real network (if makes sense)

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/o1js#1169]
Maybe start with updating the https://github.com/o1-labs/o1js/blob/main/tests/integration/simple-zkapp.js

**Comment by mitschabaude** [comment]
To me it would be interesting to run a variant of this one, which is fairly complicated and exercised a number of things: https://github.com/o1-labs/o1js/blob/main/src/examples/zkapps/dex/happy-path-with-actions.ts

**Comment by shimkiv** [comment]
[Internal details of tools needed](https://o1-labs.slack.com/archives/C028Q27R8UC/p1697731181038089?thread_ts=1697474701.828569&cid=C028Q27R8UC).

**Comment by garwalsh** [comment]
@shimkiv Note from open forum planning: include actions/reducer
