### ISSUE TITLE
Expose dummyBase64Proof()

### ISSUE THREAD

**Issue by maht0rz** [o1-labs/o1js#1185]
Would it be possible to expose `dummyBase64Proof()`, or is there a specific reason not to?

**Comment by mitschabaude** [comment]
Could be put as a static method on the `Proof` class maybe

**Comment by maht0rz** [comment]
Just to add, we also need `Pickles` exposed to do `Pickles.proofOfBase64(...)`, i'll make a PR!

**Comment by mitschabaude** [comment]
made a PR: https://github.com/o1-labs/o1js/pull/1188
