### ISSUE TITLE
Proof.fromJSON() for times in a process, failed with : RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by coldstar1993** [o1-labs/o1js#1189]
I hv a zkProgram named `JoinSplitProver `and its Proof is `JoinSplitProof`. 
after compiling  `JoinSplitProver ` in the same process, I try to deserialize a json obj to `JoinSplitProof` for almost twenty times, and failed with '**RangeError: offset is out of bounds**'. 
code as below:
![image](https://github.com/o1-labs/o1js/assets/92623877/f1f7594f-baee-48cf-9de1-7306492caac5)

error stack as below:
![image](https://github.com/o1-labs/o1js/assets/92623877/1209c56d-1ed8-4568-81b6-e70979b6dc74)

I often meet this during circuit execution(witness calc, proof gen), but first time to meet it at `Deserialization`

**Comment by Comdex** [comment]
This seems to be related to the wasm memory leak problem. Similar to executing the proof generation multiple times in a process, the wasm memory will continue to be consumed and not released in time.

**Comment by MartinMinkov** [comment]
Hey @coldstar1993, can you share the full `ZkProgram`, please? It'd be helpful for chasing down this bug :pray:
