### ISSUE TITLE
Enable compiling smart contracts along with all zkprograms it depends on

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#1207]
**Why**: Currently, `zk deploy` fails if the contract uses a ZkProgram. The goal of this issue is provide an o1js API that the zkapp-cli can use to compile a contract along with all ZkPrograms it depends on.

**How**: For example, add a new option `SmartContract.compile({ compileDependencies?: boolean })`. Figuring out the ZkProgram dependencies should happen automatically if this option is used.

**Comment by dfstio** [comment]
The better solution would be to enable SmartContract to be compiled, having only the verification key string and publicInput/publicOutput data of the ZKProgram (for example, Proof.dummy can be renamed and extended to accept the verification key string).

It will allow for significant time and memory savings when the ZKProgram proof is being generated in one process (for example, on AWS lambda) and is being used as an argument when calling the SmartContract method in a web application.

Usually, compilation of ZKProgram, especially with interactive proofs, takes longer than compilation of the SmartContract, and there is no need to force compilation of the ZKProgram in case proofs are not going to be generated, just consumed.

**Comment by mitschabaude** [comment]
Great point, thanks @dfstio! Both options might be valuable -- provide the ZkProgram verification keys, or compile all dependencies. If the ZkProgram compilation is cached, the second option might be reasonably fast as well

**Comment by zemse** [comment]
Is there any way to deploy a contract that depends on zk program?
