### ISSUE TITLE
The Escrow example no longer works after update from SnarkyJS to o1js

### ISSUE THREAD

**Issue by marekyggdrasil** [o1-labs/o1js#1218]
I have recently updated my zkApp https://mac.sqrtxx.com/ from `SnarkyJS` version `0.7.3` to `o1js` version `0.14.*` and I noticed my automated tests started to fail.

The codebase is pretty big and confusing, so before asking for help I traced down the problem and made an isolated example. It turned out that the Escrow example is no longer working:

https://github.com/o1-labs/o1js/blob/56975fcd6a905e2c361ebd564f578c0b620cce5f/src/examples/zkapps/escrow/escrow.ts

I made a whole separate repo that helps check it and reproduce, repo is

https://github.com/sqrt-xx/o1js-escrow-problem/

The way to reproduce is:

1. Clone the repo
2. Install the dependencies `npm install`
3. Run the tests `npm run test`

What happens is, Escrow contract gets compiled and deployed, then one of tests accounts does the deposit to the contract. Test fails because the balance of the contract does not increase and balance of deposit account does not decrease.

**Comment by mitschabaude** [comment]
It seems invalid to me that you run the transaction inside `Provable.asProver`. Where is the promise of the inner function supposed to be awaited? (Also, that's absolutely not the intended usage of `Provable.asProver`)

Try with this change @marekyggdrasil:
```diff
- Provable.asProver(async () => {
    const actor_pk: PublicKey = actor_sk.toPublicKey();
    const tx = await Mina.transaction(actor_pk, () => {
      zkApp.deposit(actor_pk);
    });
    await tx.prove();
    await tx.sign([actor_sk]);
    await tx.send();
-  });
```

**Comment by marekyggdrasil** [comment]
Thank you for responding so quickly @mitschabaude, I really appreciate it. Now I remember that I added `asProver` to see if it will fix another bug and then I forgot I added it.

```
 FAIL  src/Escrow.test.ts (26.253 s)
  Escrow
    ✕ generates and deploys the `Escrow` smart contract (18360 ms)

  ● Escrow › generates and deploys the `Escrow` smart contract

    [[],[["Cancelled"]],[["Update_not_permitted_balance"]],[["Cancelled"]]]

      at raise_error (ocaml/js_of_ocaml-compiler/runtime/jsoo_runtime.ml:110:3)
      at apply_json_transaction (src/lib/snarkyjs/src/bindings/ocaml/lib/local_ledger.ml:252:9)
      at Object.sendTransaction (o1js/src/lib/mina.ts:491:16)
      at sendTransaction (o1js/src/lib/mina.ts:1202:10)
      at Object.send (o1js/src/lib/mina.ts:325:16)
      at deposit (src/Escrow.test.ts:24:5)
      at Object.<anonymous> (src/Escrow.test.ts:97:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        26.394 s
Ran all test suites.
```

actually now it is `[[],[["Cancelled"]],[["Update_not_permitted_balance"]],[["Cancelled"]]]`

**Comment by mitschabaude** [comment]
Thanks @marekyggdrasil for your detailed reproduction! I can explain the error: The deposit needs to be signed by the user, but the `payerUpdate` is not signed. Try this:
```diff
- const payerUpdate = AccountUpdate.create(user);
+ const payerUpdate = AccountUpdate.createSigned(user);
```

**Comment by marekyggdrasil** [comment]
Thank you so much @mitschabaude, it works!

updated repo
https://github.com/sqrt-xx/o1js-escrow-problem/commit/dfe3b7c946c7c90564f985c6d00b3ac1f4502baf

pull-request fixing the example in o1js repo
https://github.com/o1-labs/o1js/pull/1224

**Comment by marekyggdrasil** [comment]
I will permit myself to close this issue. Thank you so much for your support @mitschabaude !

**Comment by marekyggdrasil** [comment]
@mitschabaude I have a question, here are the test accounts

https://github.com/sqrt-xx/o1js-escrow-problem/blob/dfe3b7c946c7c90564f985c6d00b3ac1f4502baf/src/Escrow.test.ts#L60-L77

the only test account that is being formally created is the deployer

https://github.com/sqrt-xx/o1js-escrow-problem/blob/dfe3b7c946c7c90564f985c6d00b3ac1f4502baf/src/Escrow.test.ts#L81-L84

given that, why does the deposit and withdraw works properly with all test accounts without throwing something like

```
    Account update #1) 0.00 MINA

    Total change: 0.00 MINA

    If there are no new accounts created in your transaction, then this sum should be equal to 0.00 MINA.
    If you are creating new accounts -- by updating accounts that didn't exist yet --
    then keep in mind the 1.00 MINA account creation fee, and make sure that the sum equals
    -1.00 times the number of newly created accounts.

    Raw list of errors: [[],[["Invalid_fee_excess"]]]
    ```

**Comment by mitschabaude** [comment]
@marekyggdrasil the test accounts are already in the ledger. So none of them need to be created. The deploy() transaction doesn't create the deployer account, it creates the zkApp account
