### ISSUE TITLE
improve MerkleMap to be easier to use and more generic

### ISSUE THREAD

**Issue by Trivo25** [o1-labs/o1js#1237]
improve MerkleMap to make it easier to use and more generic.

Some low hanging fruit is to abstract away witness verification, root assertions and root changes. some other ideas are to provide different storage types

eg:

```ts

const map = new MerkleMap();

class SimpleZkapp extends SmartContract {
  @state(Field) mapRoot = State<Field>();

  @method update(key: Field, value: Field) {
    let v = map.get(key, this.mapRoot); // this checks the witness under the hood
    map.set(key, value, this.mapRoot); // this checks the witness and calculates the new root + sets it
  }
}
```

**Comment by Saurabhpatil-dev** [comment]
Sounds cool, abstracting the more complex thing using getter and setter 😄.
Once I am done with other issue I will check and learn more and hopefully contribute. 
Till then can you please share which file would changes go ?

**Comment by Trivo25** [comment]
Hey @Saurabhpatil-dev! Great that you want to pick this up. The idea is to explore some new APIs and make working with MerkleMaps better and easier for developers - I personally dont have any strong preferences as long as the API is easy to work with :) 

https://github.com/o1-labs/o1js/blob/main/src/lib/merkle_map.ts

**Comment by LuffySama-Dev** [comment]
Hi @Trivo25 ,

Thanks for sharing details. I will start with it from tomorrow.

Thank You 😃

**Comment by LuffySama-Dev** [comment]
Hi @Trivo25 ,

I went through the code and tried to use the existing methods and create a new API.
Please let me know if this is what you were expecting ?

Questions:
- What should `getWitnessCheck()` return ?

New API Code Snippet:
```ts
  // This checks the witness under the hood for the given key and root
  getWitnessCheck(key: Field, mapRoot: Field) {
    // Calculate the witness for the given key
    const witness = this.getWitness(key);

    // Get the value from the key to compute the root
    const value = this.get(key);

    // Now we have Key, Value and mapRoot. Now we verify if witness is correct
    const [witnessRoot, _] = witness.computeRootAndKey(value); // Generating the New root using the value

    return witnessRoot.equals(mapRoot).toBoolean();
  }

  // This checks the witness and calculates the new root + sets it
  setNewRoot(key: Field, value: Field, mapRoot: Field) {
    // Checking if the witness is correct
    this.getWitnessCheck(key, mapRoot);

    // Getting the witness to generate the new root
    const witness = this.getWitness(key);

    // Generating new witness root
    const [witnessRoot, _] = witness.computeRootAndKey(value);

    // Returning the new witnessRoot to be set
    return witnessRoot;
  }

```


How it would work is :

```ts
const map = new MerkleMap();

class SimpleZkapp extends SmartContract {
  @state(Field) mapRoot = State<Field>();

  @method update(key: Field, value: Field) {
    
     // this checks the witness under the hood
    let v = map.getWitnessCheck(key, this.mapRoot); 

   // this checks the witness and calculates the new root + sets it
   this.mapRoot.set(map.setNewRoot(key, value, this.mapRoot)); 

  }
}

```


Thank You 😄
