### ISSUE TITLE
Unexpected behavior when reducing actions on live network

### ISSUE THREAD

**Issue by 45930** [o1-labs/o1js#1255]
## Summary
While building a ZkApp with actions/reducer, I have been unable to get `reduce()` to work after the first time.  This only happens on live networks, and is not reproducible in a test suite using LocalBlockchain.

### My Voting App
An example contract is [here](https://github.com/45930/Voting-Playground-o1js/blob/2e020f7ad0408492b35e0715524792e140783e78/src/TokenElection.ts), and it's deployed [here](https://berkeley.minaexplorer.com/wallet/B62qj3DfzE8FwcuDpFbwHFEVzSUsmWtcz7jBdfYJYoVLwNyt5dKB4wE)

You can see that the latest transaction fails with a precondition error:

![image](https://github.com/o1-labs/o1js/assets/36939461/590af071-5487-47be-8ea4-3896af2d6b7a)

The consensus state has already processed one action as you can see.  The state values in slots 4 and 5 have been set by the reducer and were updated from 0.

In my failing transaction, the sequence state precondition is not met by the network, so the tx fails.

![image](https://github.com/o1-labs/o1js/assets/36939461/c88469fb-4bb8-45f7-bcf3-5a937a17fb44)

I have reached this state consistently with a few different tweaks to my contract.  It's always the second call to `reduce()` and it's always the sequence state precon that's breaking.

### DFST's NFT App
I asked on discord if anyone has ever deployed a reducer successfully, and found that DFST has had the same experience.  Their code [here](https://github.com/dfstio/minanft-lib/blob/approve/experimental/reducer.test.ts) results in the same error as mine on testworld, as deployed [here](https://minascan.io/testworld/account/B62qoW2MYPzNjN2NLQCqM3sdFpCpk2XmkhGDw5x42QfSVdPFVscqwa6/zkApp?type=zk-acc)

## Repro steps

It takes a long time to repro this issue since it depends on Berkeley (or another live testnet).  My guess is that this will be reproducible with any reducer.  Unless someone can point me to the counterexample, my assumption is that reducer is broken right now.  If this is an implementation error that DFST and I made independently, there is still the problem that it passes tests on LocalBlockchain.

**Comment by 45930** [comment]
@dfstio if you want to follow along or add detail

**Comment by mitschabaude** [comment]
To investigate: is this caused by #1191?

**Comment by 45930** [comment]
> is this caused by https://github.com/o1-labs/o1js/issues/1191?

Seems highly likely.  Would explain why the precondition is incorrect (hashed in the wrong order) and why it only fails on a live network.

Maybe I can apply a monkey patch and see the results in my example.

**Comment by 45930** [comment]
Yes, reversing the fetch results worked for me, confirmed: https://berkeley.minaexplorer.com/transaction/5JutqWz2qnbxR6HiT99h3GyUoAfxw56bjBJSaH7pNXYHg5JjzgqE

**Comment by MartinMinkov** [comment]
I ran through similar testing for me as well: https://berkeley.minaexplorer.com/transaction/5JupkJuAdMWPercP2RhruADukaKk8yfYUKFJLe4kj6KC4DLAmecN
