### ISSUE TITLE
RFC: Facilitate easier ZKApp development through O1JS Support for Mina Web Node

### ISSUE THREAD

**Issue by JanSlobodnik** [o1-labs/o1js#1277]
# RFC - Facilitating easier ZKApp development through O1JS Support for Mina Web Node

## Motivation

Developers working with the Mina ecosystem must use a live Mina node in order to create ZKapps (Zero-Knowledge Applications). To facilitate the development of ZKapps, we recognize the need for a seamless and efficient testing environment. 

We want to simplify and enhance the developer experience in the Mina ecosystem by integrating O1JS support with the Mina Web Node. This will particularly help developers working on ZKapps (Zero-Knowledge Applications). 

Currently, developers face challenges in accessing or setting up OCaml nodes due to their limited availability and the complexity involved in their configuration. This integration aims to provide a more accessible and efficient development environment, reducing the technical barriers and time required to start working on ZKapps.

## Proposal

We propose the integration of O1JS support with the Mina Web Node. 

The proposed integration involves adapting the O1JS library to work seamlessly with the Mina Web Node. This entails modifications to the O1JS repository, allowing it to interact effectively with the Web Node. 

The initiative includes adding new functionalities, such as webnode.ts for data interaction, enhancing the transport layer for diverse data retrieval methods, and providing the flexibility to switch between the browser-based Web Node and server-based OCaml node setups. This integration is designed to make everything accessible from JS, offering a more streamlined approach to ZKapp development within the Mina ecosystem.

This initiative allows ZKapp developers to focus on their applications without the need to engage with the more challenging aspects of the OCaml node setup and configuration.

### Use-case

This integration can be utilized in the development of ZKapps within the Mina blockchain ecosystem. It's particularly beneficial in environments where developers require a rapid and simplified setup for testing and developing their applications. 

The enhanced O1JS library, with its Web Node compatibility, can be employed in various stages of ZKapp development, from initial prototyping to final testing, providing a versatile tool for developers working in diverse settings.

### Advantages

The integration of O1JS with the Mina Web Node offers several advantages over traditional server-based OCaml nodes:

* **Ease of Setup**: For the Web Node, all you need is a browser - it does not require any kind of installation. This greatly simplifies the initial setup process, eliminating the need for complex configuration of OCaml nodes.
* **Accessibility**: The Web Node is more readily accessible compared to OCaml server nodes, which are not always widely available.
* **User Friendliness**: It enhances the work of ZKApp developers through its more straightforward and user-friendly node interface.
* **More Options**: Adding more options for ZKApp developers is always beneficial. Developers gain the flexibility to switch between the Web Node and OCaml node, allowing them to choose the most suitable environment for their needs.
* **Resource Efficiency**: The Web node requires fewer resources compared to a full server node, making it a more economical option for developers, especially during the testing and development phases.

## Implementation

1. **Altering the O1JS Repository**: We plan to modify the O1JS repository to support this integration.
We suggest adding or modifying several files:

* We want to add webnode.ts to where we use the webnode's exposed methods to get or send different data.
* In fetch.ts, we want to add the webnode property to the global network configuration and export a function to set the Web Node inside O1JS from an external source (such as your own project which relies on O1JS). 
* We suggest adding logic that decides if the Web Node should be used instead of GraphQL in each operation. 
* In mina.ts, we suggest changing the `FeePayerSpec` typescript type to also support the field `validUntil` since it was not configurable and it was hardcoded to `undefined`. This forces a modification in account_update.ts as well to match the new type which includes `validUntil`. If implemented, it will be set to undefined only if there is no value provided.
* We want to export the `setWebnode` function so that it becomes available for external applications that rely on O1JS.
2. **Testing with the Web Node**: The primary objective is to enable developers to utilize the Web Node as an alternative to the more complex OCaml node.
3. **Transport Layer Modification**: The RFC aims to adapt the O1JS transport layer for compatibility with various transport mechanisms, such as GraphQL or direct interaction with the Web Node.
4. **Flexible Data Sources**: We aim to broaden O1JS's capability to retrieve data from sources beyond GraphQL, specifically integrating with the Web Node.
5. **Interactive Switch**: A feature will be added to allow developers to choose between interacting with the Web Node or the OCaml node. Alternatively, developers might be given the option to specify their preferred transport layer.
6. **Initial Setup Enhancements**: Instead of configuring GraphQL like before, now we can configure the Web Node and O1JS will still work. Once configured, O1JS will default to using this setup until manually altered.
7. **Minimal Modifications**: Our approach is to implement these changes with minimal alterations to the existing system.
8. **Documentation and Support**: We will regularly update documentation to provide support to developers during these changes. Well-written and comprehensive documentation will be essential for smooth adoption by the Mina developer community.
9. **Community Engagement**: We will be seeking feedback from the developer community. Their insights and feedback will be crucial in helping us finalize this process.

This RFC represents a significant step towards simplifying the ZKapp development process, making it more accessible and less cumbersome for developers within the Mina ecosystem.

**Comment by dfstio** [comment]
What are the advantages of using web node in comparison with using zk-cli? zk-cli supports running the local node by running
```
zk lightnet start
```

**Comment by mitschabaude** [comment]
It's true that we have the lightnet now. But using the web node was always an interesting idea to me. I think more options can't hurt to be honest.

Also, note that the lightnet is strictly a testing tool and will probably never be able to act as a node on a live network. I think the web node has this potential. It's integration with o1js seems like an obvious move -- everthing accessible from the JS process! 

So at a high level this RFC gets my +1, it's a good direction to pursue.

At a lower level, I want to know more about the integration in the o1js bundle. `webnode.ts` sounds like a big heavy file :) Is it Wasm, compiled from Rust?

If the webnode is reasonably big, it would be nice if its code would only be fetched if the application needs it. For that, a separate import namespace comes to mind, like `o1js/webnode`.

**Comment by dfstio** [comment]
Agree. Connecting the light web node to the mainnet or Berkeley would be great. So far, I know of only two repos that do this by using the rust code or wasm compiled from rust:
https://github.com/openmina/openmina
https://github.com/openmina/zk-web
Being able to start a web node (not only for testing) in TypeScript code would be very helpful.

**Comment by Trivo25** [comment]
This sounds exciting! Will OpenMina also work in a server enviroment (nodejs) or only web?

**Comment by directcuteo** [comment]
@mitschabaude the `webnode.ts` is not a big file. As you already pointed out, the wasm file is fetched on runtime and the file itself will live in the client application (the one that relies on `o1js`) and not in `o1js`.

As @dfstio mentioned, the working example is https://github.com/openmina/zk-web

The current issue I am facing is that I am not able to create a GitHub branch to later submit a PR. Based on [the docs](https://github.com/o1-labs/o1js/blob/31850e57411cb70f8cb013e9fea4feaa802261dd/CONTRIBUTING.md#contributing-to-o1js) I will be able to do that after this RFC is approved.

**Comment by mitschabaude** [comment]
@directcuteo the docs for how to contribute are just suggestions for a good workflow that enables the o1js team to shape the high-level approach of a change. Which is what happens here, and it's a good thing! However, getting an RFC approved has nothing to do with your technical ability of creating a GH branch to submit a PR. You just submit the PR from [a fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo)

**Comment by mitschabaude** [comment]
@directcuteo 

alternatively, it could be a different npm repo - doesn't have to be part of `o1js` even. And then there is an `o1js` API for "providing" the webnode:
```ts
import { WebNode } from `open-mina`;
import { setWebNode } from 'o1js';

setWebNode(WebNode);
```

but I'd want to avoid the implicit dependency that someone has to put something on `window`. Let's try to use modern imports for dependencies.

**Comment by dfstio** [comment]
Given the importance of the light node that allows to connect directly to the Mina blockchain, I would add the documentation about it to the main docs site https://docs.minaprotocol.com, including API short description and tutorial even in the case when it will not be included in o1js.

@directcuteo 
Will it be possible to use it in a node environment, for example, on AWS lambda? I see that opening.com is able to connect to the blockchain within 5 seconds, and the maximum run time of the lambda is 15 minutes.

**Comment by mitschabaude** [comment]
> However, in this use case, the Web Node presents more advantages for developers compared to the server-based Openmina node due to its ease of use, accessibility, and lower resource requirements.

Would be nice to make a version of that low-resource web node also for Node.js 👀
