### ISSUE TITLE
Be stricter about ways to create UInt64/32

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#1286]
**Why**: Currently, it's very easy to create `UInt64` or `UInt32` from a `Field` without range-checking it, without given any hint that this is unsafe. For `Bool` we do a much better job: the only way to create it from a `Field` is with `Bool.Unsafe.ofField()`

**How**: 
* Remove `Field` as input type from `UInt64.from()`. Replace with something like `UInt64.Unsafe.fromField()`
* Remove `Field` as possible constructor input. The tricky thing is that `UInt64` really consists of 1 Field, so we need a way to construct it from field at least in internal methods. There are two ways around this:
  * make the constructor take a `FieldVar` instead of a `Field`, so that creating it from a `Field` becomes a less visible and more low-level operation. This is how `Bool` does it.
  * or make the constructor private externally. This makes the breaking change more breaking though.

**Comment by barriebyron** [comment]
Please advise @mitschabaude can you help identify the required doc updates?

**Comment by mitschabaude** [comment]
@barriebyron the UInt64 API changed, so this is about fixing type errors that turn up when switching to the latest o1js version in doc examples

**Comment by barriebyron** [comment]
Can you help me identify the examples that need updating?
