### ISSUE TITLE
Attach arbitrary metadata to Custom Token?

### ISSUE THREAD

**Issue by emlautarom1** [o1-labs/o1js#1298]
Following the official docs at https://docs.minaprotocol.com/zkapps/o1js/custom-tokens we were wondering if it's possible to attach custom metadata to tokens minted by a Smart Contract. Ideally, we would like to have something similar to the following:

```typescript
import { SmartContract, method } from "o1js";

export class MintExample extends SmartContract {
  @method mint(account: String) {
    this.token.mint({
      address: this.sender,
      amount: 1,
      metadata: `${this.account.tokenSymbol}#${account}`
    });
  }
}
```

Is it possible to do something like this currently with `o1js`?

**Comment by mitschabaude** [comment]
No, a token is just a balance and a token symbol. To attach metadata I recommend onchain state or events or actions!
