### ISSUE TITLE
Improve o1js repo structure

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#1329]

**Comment by LuffySama-Dev** [comment]
Hey @mitschabaude ,

Good Day!!
I would like to help you with this if possible.

Thanks Luffy 😃

**Comment by mitschabaude** [comment]
Hey @LuffySama-Dev I appreciate, but IMO this is an o1-internal issue. Repo structure should be decided/changed within the people that work on this repo every day

**Comment by LuffySama-Dev** [comment]
Hi @mitschabaude ,

No Problem. If there is anything else you can think where I can help please let me know !!

Thanks Luffy 😃
