### ISSUE TITLE
ECDSA signature recovery 

### ISSUE THREAD

**Issue by TtheBC01** [o1-labs/o1js#1343]
Is anyone on the o1js team currently working on an ECDSA signature recovery method or does it currently happen to be on the roadmap? It'd be super helpful to have such a method when the user's public key is not readily available but their signature and address is.

**Comment by mitschabaude** [comment]
> I'd be super helpful to have such a method when the user's public key is readily available but their signature and address is.

@TtheBC01 I assume you mean when the public key is _not_ available, so you want to recover the public key?

Do you need prove the public key recovery, or is it enough to have it outside provable code?

**Comment by TtheBC01** [comment]
Sorry, i wrote that late last night and didn't grammar check it (I edited my question so it actually makes sense now). 

So after sleeping on it and also reading your reply here, I realize that it is sufficient to recover the public key outside the provable code, then just use the existing `verifyECDSA` method as is.
