### ISSUE TITLE
Bug: `SmartContract`s don't work when ES2022 and ESNext are targeted.   

### ISSUE THREAD

**Issue by BerzanOrg** [o1-labs/o1js#1380]
## Description
`SmartContract.compile` method doesn't work when `compilerOptions.target` is set to `"ES2022"` or `"ESNext"` inside `tsconfig.json` file.

It works as expected when `"ES2020"` or `"ES2021"` is targeted.

## Dependency Versions

**o1js:  0.15.2**

## Weird Error Message
It gives the weird error message below when `"ES2022"` or `"ESNext"` is targeted.
The code responsible for this error message resides in [here](https://github.com/o1-labs/o1js/blob/659c203a638eb13ae04846163c09e4da50bb6dae/src/lib/state.ts#L205).

```
Error: get can only be called when the State is assigned to a SmartContract @state.
```

## Reproducible Code

> index.ts

```ts
import { Field, SmartContract, State, method, state } from "o1js"

class MyContract extends SmartContract {
    @state(Field) count = State<Field>()
    @method increment() {
        this.count.set(this.count.getAndRequireEquals().add(1))
    }
}

await MyContract.compile()
```
> tsconfig.json
```json5
{
    "compilerOptions": {
        "target": "ES2022", // `"ESNext"` doesn't work too. But `"ES2020"` and `"ES2021"` work.
        "module": "ESNext",
        "outDir": "./build",
        "rootDir": ".",
        "strict": true,
        "strictPropertyInitialization": false, 
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "esModuleInterop": true,
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "allowJs": true,
        "declaration": true,
        "sourceMap": true,
        "noFallthroughCasesInSwitch": true,
        "allowSyntheticDefaultImports": true
    },
    "include": ["./src"]
}
```

**Comment by mitschabaude** [comment]
Hey @BerzanOrg, thanks for reporting!

Can you try with this tsconfig option that o1js uses:
```json
{
  "compilerOptions" : {
    "useDefineForClassFields": false,
  }
}
```

**Comment by BerzanOrg** [comment]
Thank you, Gregor. 
Setting `compilerOptions.useDefineForClassFields` to `false` makes it work for both `"ES2022"` and `"ESNext"` targets.

**Comment by mitschabaude** [comment]
TODO for myself: add this to the zk project tsconfig

**Comment by LuffySama-Dev** [comment]
Hi @mitschabaude ,

Out of curiosity, where will you add this change ? 

Thanks 😃

**Comment by mitschabaude** [comment]
> Out of curiosity, where will you add this change ?

@LuffySama-Dev here: https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/tsconfig.json
