### ISSUE TITLE
[FIXUPS for mina-signer files RFC]

### ISSUE THREAD

**Issue by robrobbins** [o1-labs/o1js#1415]
1. The tests in /mina-signer/tests/* will not compile/run because of an incorrect path to the `dist` directory
2. fixups for the `fieldToHex` method suggested by @mitschabaude in #1404 

I have posted a PR here #1414

**Comment by mitschabaude** [comment]
Hey @robrobbins you don't need an "RFC" upfront before PRing small fixes :D
