### ISSUE TITLE
chore: find a convention for file names and apply them across the code base

### ISSUE THREAD

**Issue by Trivo25** [o1-labs/o1js#1429]
We previously talked about this; for file names, we use both `under_scores.file` and `normal-scores.file` in the code base. We should agree on a naming convention for file names (and folders), apply and stick to them 

I am for `normal-score.file` and `/normal-score`

**Comment by mitschabaude** [comment]
+1, and we already agreed on exactly that convention a while ago. and we did start to apply that convention to new files, but I'm also in favor changing all the old files

it actually seems like a reasonable time to do this now, with not many large pending PRs open

**Comment by mitschabaude** [comment]
done :D
