### ISSUE TITLE
make `mainnet` (hash) prefixes the default

### ISSUE THREAD

**Issue by Trivo25** [o1-labs/o1js#1445]
Once mainnet hits, we have to make sure that all default (hash) prefixes are set to `mainnet`. Currently, the default is set to `testnet` 

some examples

in `src/lib/mina.ts`

```ts
let minaNetworkId: NetworkId = 'testnet';
```

in `src/mina-signer/mina-signer.ts`

```ts
let signature = sign({ fields }, privateKey_, network ?? 'testnet');
```

**Comment by mitschabaude** [comment]
why is mainnet the better default?

**Comment by Trivo25** [comment]
I feel like less configuration effort would lead to a more seamless integration with the main network you want to interact with and interacting with a different network should require an explicit configuration to do so - but both works

**Comment by L-as** [comment]
relevant: #1492

**Comment by Trivo25** [comment]
I think I have changed my mind - I believe having `testnet` as default is better

**Comment by Trivo25** [comment]
Closing for now, can reopen if relevant again
