### ISSUE TITLE
`CircuitString.toString` replaces characters

### ISSUE THREAD

**Issue by emlautarom1** [o1-labs/o1js#1451]
I would expect the following operation to be valid:

```typescript
describe('CircuitString', () => {
  test('`Character[]` to `CircuitString`', () => {
    let msg = `Hello,\n\nHow are you?`;
    let arr = msg.split('').map(c => Character.fromString(c));
    let cs = CircuitString.fromCharacters(arr);
    let msg_ = cs.toString();

    expect(msg).toEqual(msg_);
  });
});
```

That is, taking a `JS string -> Character[] -> CircuitString -> JS string` should result into the same string (as long as the string length is less than `CircuitString.length`).

This does not seem to be the case, and the culprit seems to be `toString`: see https://github.com/o1-labs/o1js/blob/b0fb1c8009465fbf87b11d319c3b3d620b56ebc1/src/lib/string.ts#L137. It seems to be an intentional decision, but this has bitten us during testing. Why is it done like this?

**Comment by mitschabaude** [comment]
I assume the intention here was to filter out the 0x00 characters that we use as padding? although it doesn't seem to be the right way to do that
