### ISSUE TITLE
`CircuitString.fromCharacters` does not respect `maxLength`

### ISSUE THREAD

**Issue by emlautarom1** [o1-labs/o1js#1452]
I'm not sure if this is intentional, but we assume that all `CircuitString`'s respect the `maxLength` property as defined:

https://github.com/o1-labs/o1js/blob/b0fb1c8009465fbf87b11d319c3b3d620b56ebc1/src/lib/string.ts#L40

This is actually not the case when using `CircuitString.fromCharacters`:

```typescript
let msg = Array(2000).fill('a').join('');
let arr = msg.split('').map(c => Character.fromString(c));
let cs = CircuitString.fromCharacters(arr);
```

I would expect it to have the same constraints as the `CircuitString.fromString` method as defined:

https://github.com/o1-labs/o1js/blob/b0fb1c8009465fbf87b11d319c3b3d620b56ebc1/src/lib/string.ts#L141-L143

If this check is not in place, we can construct `CircuitString`s of more than `maxLength` characters, which then creates problems in, for example, `assertEquals`

**Comment by mitschabaude** [comment]
doesn't sound very intentional
