### ISSUE TITLE
Deploy infrastructure to add o1js benchmarks to CI

### ISSUE THREAD

**Issue by garwalsh** [o1-labs/o1js#1473]
This can be set up using [the first benchmark](https://github.com/o1-labs/o1js/issues/923). Others can be added later. 

We require CI to run benchmarks and generate a report. In the long term we want CI to fail if performance is degraded but what does that mean exactly? What constitutes failure, do we need the ability to override? I think we should add the report but not fail the build in the first version.

Similarly, please note that a chart of historic performance may be added but is also not a requirement of this issue / first version.

**Comment by shimkiv** [comment]
Using results of #1486 do the following:
- Create secure cloud VM;
- Configure DNS records (*.o1js.dev?);
- Deploy secured benchmarking infra;
- Configure persistence layer (InfluxDB) daily backups and offloading to some cloud storage.
- Provide information regarding the access to deployed services.
