### ISSUE TITLE
Running Jest with `o1js` template

### ISSUE THREAD

**Issue by Pfed-prog** [o1-labs/o1js#1495]
Gm, I am trying to figure out how to run jest with `o1js` and I have failed tremendously so far. 

For example, after i clone this repo and run `yarn jest` I get Test Suites: 18 failed, 18 total

I am not sure how run tests with o1js correctly, 

I have tried to use https://github.com/MinaFoundation/soulbound-tokens/blob/main/jest.config.js config from Soulbound NFTs, but unfortunately it does not seem to work either
<img width="731" alt="image" src="https://github.com/o1-labs/o1js/assets/66903336/c9e17149-ed65-4542-80e1-c9814abfc001">

**Comment by mitschabaude** [comment]
Hey @Pfed-prog are you using the zkapp CLI `zk project` template? If yes, here are some ideas:
* If TS tells it "cannot find module 'o1js'..." then the first thing to check is if you have installed: `npm i`
* The template doesn't use `yarn` so maybe things will be smoother if you just use npm to run scripts: `npm test`

**Comment by mitschabaude** [comment]
> For example, after i clone this repo

If you're talking about the o1js repo, there should be notes in the `README-dev.md`:
* Run all Jest tests with `npm test`
* Run a single test with `./jest ./path/to/file`

**Comment by Pfed-prog** [comment]
Thank you ver much this works.
