### ISSUE TITLE
`Transaction.prove` and `Transaction.send` result method chaining

### ISSUE THREAD

**Issue by harrysolovay** [o1-labs/o1js#1514]
Hi o1js community and maintainers. I'm new to this library + zkApps in general, so please take my thoughts with a grain of salt.

I'm contemplating the following code.

```ts
let tx = await Mina.transaction(id, () => { /* ... */ })
await tx.prove()
let pending = await tx
  .sign([key])
  .send()
await pending.wait()
```

Could we enable a fully-chained experience?

```ts
await Mina
  .transaction(id, () => { /* ... */ })
  .prove()
  .sign([key])
  .send()
  .wait()
```

I suppose `prove` and `send` would need to return promise subtypes (`ProveResult` and `SendResult` respectively).

```ts
type ProveResult = Promise<(Proof<ZkappPublicInput, undefined> | undefined)[]> & {
  sign: (additionalKeys?: PrivateKey[] | undefined) => Promise<Transaction> & {
    send(): SendResult
  }
}

type SendResult = Promise<Mina.PendingTransaction> & {
  wait: (options?: {
    maxAttempts?: number | undefined;
    interval?: number | undefined;
  } | undefined) => Promise<Mina.IncludedTransaction>
}
```

Some follow-up thoughts + questions:

- this would be non-breaking
- are there reasons to keep these steps non-chainable?
- a given promise subtype could contain a reference to the step/promise off of which it was chained, incase a direct reference is required

**Comment by mitschabaude** [comment]
to me this seems to add complexity without a clear benefit. With `prettier` formatting your non-chained example even uses less lines of code than the chained one

**Comment by harrysolovay** [comment]
Apologies for not clearly articulating the benefits:

- 1 `await` instead of 4 `await`s.
- No need to define (and therefore come up with) variable names for (A) the tx and (B) the pending counterpart. This would be especially useful in scopes that create/prove/sign/send/wait multiple txs, as devs wouldn't need to spend time considering names for variables that are not subsequently referenced.
- Legibility gains

This last benefit I listed is subjective... but I do believe the chained/fluent equivalent would be––for most developers––more legible/preferable.

I can close this issue if you still disagree. Thank you for hearing me out + considering this approach.

**Comment by harrysolovay** [comment]
That utility would work great! Alternatively, we could create dedicated promise subclasses, as to avoid bloating the return type (the intersection of `Promise<T>` with the mapped type might be a bit intimidating).

```ts
const a = Mina.transaction(id, () => { /* ... */ }) // `CreateTransactionPending`
const b = a.prove() // `ProoveTransationPending`
const c = b.sign([key]) // `SignTransactionPending`
const d = c.send() // `SendTransactionPending`
const e = d.wait() // `Promise<FinalizedTransaction>`
```

The downside of dedicated subclasses: it obfuscates _thenability_... the `Pending` postfix should mitigate this downside. Still a risk. The return signature you suggested is clearer, although more verbose. What's preferable?

**Comment by mitschabaude** [comment]
> The return signature you suggested is clearer, although more verbose

It would only be _that_ verbose in the source code, in the compiled type it would be more similar to [your suggestion](https://github.com/o1-labs/o1js/issues/1514#issue-2205644556) and fine I think (better than a custom class)

**Comment by harrysolovay** [comment]
Agreed: `mapPromise` also allows the proxied method tsdocs to flow through. Quick question re. implementation:

I'm looking at the overload signatures of [`src/lib/mina/transaction.ts#transaction`](https://github.com/o1-labs/o1js/blob/95e5d419e86be95c5fd4803d6679e2ea6aaaaea3/src/lib/mina/transaction.ts#L471)––how would you recommend modifying these overloads? My sense was that we would rely on inference from `mapPromise`, but that doesn't seem to be an option given how it's currently set up.

**Comment by mitschabaude** [comment]
> I'm looking at the overload signatures of [src/lib/mina/transaction.ts#transaction](https://github.com/o1-labs/o1js/blob/95e5d419e86be95c5fd4803d6679e2ea6aaaaea3/src/lib/mina/transaction.ts#L471)––how would you recommend modifying these overloads?

Maybe the return of `mapPromise` should be made its own type `MapPromise<T, K>` and that used?

**Comment by mitschabaude** [comment]
Hey @harrysolovay do you want to create a PR? this looks like a great start!

**Comment by mitschabaude** [comment]
> The src/bindings submodule is failing to clone on my machine

It's just very big so might take a while

**Comment by harrysolovay** [comment]
Just wanted to follow up. I intend to take a pass at this soon.

I have been second-guessing `mapPromise`. The promise subclassing approach may be more straight-forward. Currently, `PendingTransaction`, `IncludedTransaction` and `RejectedTransaction`––stages in the desired chaining DX––are the result of using the `Pick` utility type and intersecting on a common `Transaction` type. This + `mapPromise` might start to break down in some cases. For instance...

> ```ts
> await Mina
>   .transaction(id, () => { /* ... */ })
>   .prove()
>   .sign([...privateKeys])
> ```
