### ISSUE TITLE
`Local.testAccounts` vs. `noUncheckedIndexAccess`

### ISSUE THREAD

**Issue by harrysolovay** [o1-labs/o1js#1516]
With [`noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) enabled (best practice), the TS checker errors on the inner destructuring of `testAccount` elements. 

```ts
let [{ privateKey, publicKey }] = Local.testAccounts
//   ~~~~~~~~~~~~~~~~~~~~~~~~~
//   ^
//   Property 'privateKey' does not exist on type '{ publicKey: PublicKey; privateKey: PrivateKey; } | undefined'. ts(2339)
```

Is there a reason not to type the length of `Local.testAccounts`? We could do so with [the `TupleN` type](https://github.com/o1-labs/o1js/blob/95e5d419e86be95c5fd4803d6679e2ea6aaaaea3/src/lib/util/types.ts#L28-L32) right [here](https://github.com/o1-labs/o1js/blob/95e5d419e86be95c5fd4803d6679e2ea6aaaaea3/src/lib/mina/local-blockchain.ts#L61-L64). This would spare the developer of needing to override the checker.

```ts
let [{ privateKey, publicKey }] = Local.testAccounts // no TS error, sweet!
```

**Comment by mitschabaude** [comment]
Damn i didn't know `noUncheckedIndexAccess`. I love it!
