### ISSUE TITLE
seemingly-innocuous code producing checker depth error (2589)

### ISSUE THREAD

**Issue by harrysolovay** [o1-labs/o1js#1537]
I see no circular type reference in the following.

```ts
import { Struct, UInt64, MerkleList } from "o1js"

export class ApprovalId extends UInt64 {}
export class Approvals extends MerkleList<ApprovalId> {}

export class TokenAccount extends Struct({
  balance: UInt64,
  approvals: Approvals,
}) {}
```

Any idea why this is producing a type instantiation depth error?

[TS playground here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRlArgYxgGjgVQEkA7GANgBY8BZAUygGsAbWgGWAGd4BfOAMygQQcAEQQAjACsOIgFCzaAD0iw4mJgEMOHOAEEwYQQDcNTQgBM4SmLWLmdRUpUTcFy6PHVad+wxBNMOta29nB0jCzsXAA8vsamFgB8LvJKKp6a2nAAKhAMtrqYmBDopFaKNnY6qBjYABQIsnBwAEamGsSYtABcBCTkVE1wGgbxgb1x-qYcOLLcAJQpQA).

**Comment by mitschabaude** [comment]
```ts
import { Struct, UInt64, MerkleList } from "o1js"

export class ApprovalId extends UInt64 {}
export class Approvals extends MerkleList.create(ApprovalId) {}

export class TokenAccount extends Struct({
  balance: UInt64,
  approvals: Approvals.provable,
}) {}
```

**Comment by harrysolovay** [comment]
Thank you for the quick reply and (temporary (?)) fix. I can confirm that resolved the depth error. Why is `MerkleList` a class and not a class factory like `Struct`?

**Comment by mitschabaude** [comment]
We need base classes for generic classes because of we return them directly from a function, the type get butchered by TS in the exported `d.ts` file. For example, method arguments that are instances of the class become `any`.

For `Struct` its different because we're explicitly defining the interface that the function returns.
