### ISSUE TITLE
Make MerkleTree.nodes public or refactor MerkleTree to not use depreciated in o1js 0.18.0 CircuitValue and arrayProp

### ISSUE THREAD

**Issue by dfstio** [o1-labs/o1js#1549]
The MerkleTree.nodes is private:
```typescript
class MerkleTree {
  private nodes: Record<number, Record<string, Field>> = {};
  private zeroes: Field[];
  ...
```
https://github.com/o1-labs/o1js/blob/main/src/lib/provable/merkle-tree.ts#L28

I need to serialize MerkleTree in my project, so I need access to nodes. In o1js 0.17.0, I have copied the MerkleTree code and defined the toJSON() method. With o1js 0.18.0, CircuitValue and arrayProp, which MerkleTree is using, are depreciated, and this code does not work anymore. I can copy CircuitValue and arrayProp code also, but a better way is to make MerkleTree.nodes public.

See also https://github.com/o1-labs/o1js/issues/1482

**Comment by mitschabaude** [comment]
thanks for reporting this, I made https://github.com/o1-labs/o1js/pull/1555

**Comment by dfstio** [comment]
Thanks a lot!
