### ISSUE TITLE
'src/tests/transaction-flow.ts' issues

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/o1js#1565]
- As discussed with @MartinMinkov the test has missed reflection of async circuits feature (yet somehow it worked on CI).
  - [deploy](https://github.com/o1-labs/o1js/blob/028b65ae5385397db655d847c197b12d69e4f71c/src/tests/transaction-flow.ts#L184)
  - [incrementCounter](https://github.com/o1-labs/o1js/blob/028b65ae5385397db655d847c197b12d69e4f71c/src/tests/transaction-flow.ts#L273)
- Also I noticed issues with Local cases against the `mainnet` network ID.

**Comment by mitschabaude** [comment]
@shimkiv @MartinMinkov I disagree, the two places in the code that you mention take into account promises correctly. both are written as normal callbacks (no `async` keyword) which _return a `Promise`_, which is equivalent to an async function that awaits the promise internally

**Comment by mitschabaude** [comment]
> Also I noticed issues with Local cases against the mainnet network ID.

this is important to debug!

**Comment by shimkiv** [comment]
#1579
