### ISSUE TITLE
Mina-signer: mention private key conversion function when `PrivateKey.fromBase58()` fails

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#1568]
Several users of mina-signer have been trying to use it with out of range private keys and ran into an error.

That's why we introduced a conversion function to support these private keys.
That function should be mentioned in the error message, whenever `PrivateKey.fromBase58()` fails with an error containing
```
Scalar: inputs larger than XXX are not allowed, got YYY
```

**Comment by emirsoyturk** [comment]
Hey I would like to help this issue if it is still available. @mitschabaude

**Comment by mitschabaude** [comment]
@emirsoyturk yes that would be great! It's available

**Comment by emirsoyturk** [comment]
Just opened a PR
