### ISSUE TITLE
Make error message for adding a state variable more user friendly

### ISSUE THREAD

**Issue by garwalsh** [o1-labs/o1js#1571]
Reported by Ivan. Let's update this error to something that is more descriptive and helpful to the developer.

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVJhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a08138f73ae64c682e0a60175dd357cd45f9396a/image.png" alt="image.png" />

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVZhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c6f729fc9eef42268642d6fb23cba96e5c096f7/image.png" alt="image.png" />

**Comment by harrysolovay** [comment]
I'm getting a `Non-Image content-type returned` error whenever I try to access the images in your issue body. Can you please re-upload?
