### ISSUE TITLE
Feature request: Adding devnet to mina-signer

### ISSUE THREAD

**Issue by iam-dev** [o1-labs/o1js#1600]
The ability to use devnet using mina-signer

```
import Client from 'mina-signer';
const client = new Client({ network: 'devnet' });
```

**Comment by mitschabaude** [comment]
The correct network id to use with devnet is 'testnet', so we already support devnet.

The network id is supposed to prevent replays of testnet transactions on mainnet. So it only needs to distinguish between testnet and mainnet, not what kind of testnet (the custom option is intended to support alternative _mainnets_, like L2s)

**Comment by iam-dev** [comment]
This is misleading because auro wallet gives back devnet as connected network, which mean mina-signer will error using devnet
```
const requestedNetwork = await (window as any)?.mina?.requestNetwork().catch((err: any) => err);
        console.log('requestedNetwork', requestedNetwork);
        ```

**Comment by iam-dev** [comment]
My use case will be:
- User signin to zkApp using Auro Wallet (Web3 login with his signature
- User choose devnet as network within Auro wallet
- Our zkApp verify this signature using mina-signer
- mina-signer will try to use "devnet" as client
- signature verification will fail
-

**Comment by mitschabaude** [comment]
@iam-dev I guess the answer is, `requestedNetwork` returned by Auro wallet just doesn't have the same meaning as the `network` parameter of mina-signer, that's why you can't plug in one of them into the other.

In the case of mina-signer, it just wants to know whether this is a testnet or a mainnet, and nothing else. We should document that better.

Adapting your use case is trivial: If Auro returns something else than `"mainnet"`, use `"testnet"` in mina-signer.

**Comment by mitschabaude** [comment]
@iam-dev another thing to note. If you aren't signing transactions, but just use `signFields()` from `mina-signer`, to create signatures which are consumed by zkapps, then the `network` parameter doesn't matter at all.

**Comment by mitschabaude** [comment]
> Our zkApp verify this signature using mina-signer

@iam-dev finally, I hope it's obvious but just to make sure: mina-signer is not creating constraints and can't be used to verify a signature as part of a zkApp `@method`

**Comment by iam-dev** [comment]
It's clear for me now, I had a backend working that validate signature to signin with Web3, which also uses mina-signer. I solved it with a workaround using "testnet" and works like a charms. I guess this is a workable workaround

**Comment by iam-dev** [comment]
Thanks @mitschabaude  for clearing this up for me
