### ISSUE TITLE
Bug: `LocalBlockchain` does not update contract state unless some `SmartContract` state is explicitly called

### ISSUE THREAD

**Issue by Pfed-prog** [o1-labs/o1js#1602]
`LocalBlockchain` does not update contract state unless any contract state is explicitly called

```ts
it('deploys app', async () => {
    await deployNFTContract(
      pkAdmin,
      nftContractPrivateKey,
      proofsEnabled,
      live
    );
});

it('inits app root', async () => {
    await initNFTContractRoot(
      pkAdmin,
      pkSender,
      map,
      nftContract,
      nftArray.length,
      live
    );
  });
```

produces `FieldVector.get(): Index out of bounds, got 0/0 ` error in `initNFTContractRoot`

But it is fixed by calling a state in smart contract
```ts
  it('deploys app', async () => {
    await deployNFTContract(
      pkAdmin,
      nftContractPrivateKey,
      proofsEnabled,
      live
    );
    expect(nftContract.admin.get().toBase58()).toBe(pubAdmin.toBase58());
  });
```

**Comment by Pfed-prog** [comment]
`Prove.log()` also seems to stop logging before private function

**Comment by mitschabaude** [comment]
One general suggestion: check that you always await contract calls

Other than that it's very hard to say anything without seeing the code of those functions you call

**Comment by Pfed-prog** [comment]
Downgraded to 0.17.0 as it does not force me to have async transactions and async deploy.

But I face a very similar errors when I call contract methods in async.

**Comment by Pfed-prog** [comment]
@mitschabaude I am not sure where the error comes from exactly, but it has definitely to do with calling async contract methods
<img width="1237" alt="image" src="https://github.com/o1-labs/o1js/assets/66903336/1e4b5fb0-eeea-4d3e-9f81-e393a4e5a88c">

I am not sure if i should declare async private and public methods
or something is off with how i call transactions, but it definitely works without async
