### ISSUE TITLE
Payload Too Large error is thrown on devnet for transactions involving 3 zkApp accounts

### ISSUE THREAD

**Issue by dfstio** [o1-labs/o1js#1607]
The following error is thrown on devnet with o1js 0.18.0:
```
Error: Transaction failed with errors:
- {"statusCode":413,"statusText":"Payload Too Large"}
    at Object.send (/Users/mike/Documents/DeFi/MinaNFT/minanft-lib/node_modules/o1js/dist/node/index.cjs:20902:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at sendTx (/Users/mike/Documents/DeFi/MinaNFT/minanft-lib/experimental/payload.issue.test.ts:640:14)
    at Object.<anonymous> (/Users/mike/Documents/DeFi/MinaNFT/minanft-lib/experimental/payload.issue.test.ts:601:5)
```
The same code works as intended on the local blockchain and Zeko. It occurs only on tx that include three zkApp accounts:
- 2 usual zkApp accounts
- 1 token zkApp account

The code to reproduce the issue:
https://github.com/dfstio/minanft-lib/blob/master/experimental/payload.issue.test.ts

It may be related to https://github.com/o1-labs/o1js/issues/1245#issuecomment-1972951258

**Comment by dfstio** [comment]
The tx that is causing this error:
[payload-issue.json](https://github.com/o1-labs/o1js/files/15064587/payload-issue.json)

**Comment by shimkiv** [comment]
Hey @dfstio thanks for the issue reported!
I noticed that you save txn payload into the file [before](https://github.com/dfstio/minanft-lib/blob/443313485b48b14fda072010d28e0fd59c5aab23/experimental/payload.issue.test.ts#L609-L610) txn gets proved that most likely will include additional "weight" to the request.
I also noticed that you're using the Mina Explorer's [Proxy](https://github.com/dfstio/minanft-lib/blob/443313485b48b14fda072010d28e0fd59c5aab23/src/networks.ts#L62C2-L62C53) to broadcast the transaction (send payload). Most likely that proxy has some request payload size limits. Can you please confirm if the issue happens to you using other broadcasting services as well (maybe your own node with graphql endpoint enabled, or the Lightnet)?

**Comment by dfstio** [comment]
I've tested, in addition, the `https://api.minascan.io/node/devnet/v1/graphql` endpoint and Lightnet; the error is being thrown only when using `https://proxy.devnet.minaexplorer.com/graphql.`

I've moved the code that serializes the tx after `tx.prove()`; below are the files that were produced for all three endpoints:
[payload-issue-lightnet.json](https://github.com/o1-labs/o1js/files/15066710/payload-issue-lightnet.json)
[payload-issue-minaexplorer.json](https://github.com/o1-labs/o1js/files/15066711/payload-issue-minaexplorer.json)
[payload-issue-minascan.json](https://github.com/o1-labs/o1js/files/15066712/payload-issue-minascan.json)

**Comment by dfstio** [comment]
Discussion on discord:
https://discord.com/channels/484437221055922177/583400552487059546/1232023018276917349

**Comment by shimkiv** [comment]
> the error is being thrown only when using `https://proxy.devnet.minaexplorer.com/graphql.`

Thank you! I think we also need to check with other public txns broadcasting services if they have request size limits.
We are going to raise it.

**Comment by dfstio** [comment]
The issue is resolved by increasing the limit on  `https://proxy.devnet.minaexplorer.com/graphql` and tx is now successful: 
https://devnet.minaexplorer.com/transaction/5JuoKLjxvdYCHtByWmFR43uZXTgwtDUJvxhpu5N3qjpZrUZV8kMh
