### ISSUE TITLE
Duplicate sections in README-dev.md

### ISSUE THREAD

**Issue by dfstio** [o1-labs/o1js#1620]
https://github.com/o1-labs/o1js/blob/main/README-dev.md has the following duplicate sections at the beginning of the file:

https://github.com/o1-labs/o1js/blob/main/README-dev.md#o1js-readme-dev
https://github.com/o1-labs/o1js/blob/main/README-dev.md#o1js-readme-dev-1

https://github.com/o1-labs/o1js/blob/main/README-dev.md#prerequisites
https://github.com/o1-labs/o1js/blob/main/README-dev.md#prerequisites-1

https://github.com/o1-labs/o1js/blob/main/README-dev.md#building-o1js
https://github.com/o1-labs/o1js/blob/main/README-dev.md#building-o1js-1

**Comment by shimkiv** [comment]
@dfstio thank you for issue posted!
