### ISSUE TITLE
Custom token transfers don't work based on the order of account updates.

### ISSUE THREAD

**Issue by berzanorg** [o1-labs/o1js#1636]
There was no issue when I was using o1js v0.17.0, but after I updated my project to v1.1.0 it started to throw the error below.

```
Error: Cannot push to an immutable forest
```

This code works: (fixed version)
```ts
const mintTx = await Mina.transaction(userAccount2, async () => {
    AccountUpdate.fundNewAccount(userAccount2)
    token.transfer(userAccount2, userAccount1, UInt64.from(1000))
})
```

But this doesn't work: (old version)
```ts
const mintTx = await Mina.transaction(userAccount2, async () => {
    token.transfer(userAccount2, userAccount1, UInt64.from(1000))
    AccountUpdate.fundNewAccount(userAccount2)
})
```

And throws this error, `Error: Cannot push to an immutable forest`.

You can replicate the same error just by using a basic custom token contract like below:
```ts
export class TokenContract extends BaseTokenContract {
    @method async mint(amount: UInt64, receiver: PublicKey) {
        this.internal.mint({
            address: receiver,
            amount,
        })
    }

    @method async approveBase(forest: AccountUpdateForest) {
        this.checkZeroBalanceChange(forest)
    }
}
```

Maybe having a more clear error message would make it easier to debug.
Or if it is possible, making both of the snippets work like in the previous versions would be very good.

**Comment by mitschabaude** [comment]
@berzanorg you're just missing an `await`:

```diff
const mintTx = await Mina.transaction(userAccount2, async () => {
-  token.transfer(userAccount2, userAccount1, UInt64.from(1000))
+  await token.transfer(userAccount2, userAccount1, UInt64.from(1000))
   AccountUpdate.fundNewAccount(userAccount2)
})
```

**Comment by mitschabaude** [comment]
It seems hard to give consistently good error messages for this problem :/

Here's what happens:

* Missing the await just means that the `fundNewAccount()` call happens while we are still within the context of the `transfer()` call
* So, `AccountUpdate.fundNewAccount()` creates an account update and tries to push it as a child update of the `transfer()` call
* However, `transfer()` fully "finalizes" its forest of child account updates, so adding another child creates an error
  * This finalizing happens as follows:
     * `transfer()` creates an `AccountUpdateForest`, and passes it to the internal `approveBase()`
     * your `approveBase()` internally calls `TokenContract.forEachUpdate()` which calls `this.approve(forest)`, which makes the input forest be the final account update layout of this method call
