### ISSUE TITLE
compiling `merkle-zkapp` example 

### ISSUE THREAD

**Issue by Pfed-prog** [o1-labs/o1js#1696]
`src/examples/zkapps/merkle-tree/merkle-zkapp.ts` example does not compile with  `"o1js": "1.3.1"`

Here is a template with the `merkle-zkapp.ts` code.

https://github.com/Pfed-prog/Mina-Template

`yarn compile`
"compile": "rm -rf build && tsc",

output

<img width="665" alt="image" src="https://github.com/o1-labs/o1js/assets/66903336/33c97d7a-3285-42f1-9096-4654dd7d235e">

**Comment by mitschabaude** [comment]
the error doesn't seem to have anything to do with the example itself.
maybe you're trying to compile o1js with a version of TS it's not compatible with?
I'd try to upgrade TS.

@Pfed-prog As an aside, I didn't see a `package.json` in your project, you're git-ignoring all `.json` files, that seems error-prone to me.

**Comment by Pfed-prog** [comment]
> the error doesn't seem to have anything to do with the example itself. maybe your TS version is not compatible with o1js? I'd try to upgrade TS.
> 
> @Pfed-prog As an aside, I didn't see a `package.json` in your project, you're git-ignoring all `.json` files, that seems error-prone to me.

Yes, excuse me, added dependabot as well. Package json and tsconfig is back.
