### ISSUE TITLE
Considering `ZkProgram` Interface

### ISSUE THREAD

**Issue by harrysolovay** [o1-labs/o1js#1701]
Looking at [the recursion docs](https://docs.minaprotocol.com/zkapps/tutorials/recursion), I think some subtle changes would result in greater legibility. Let's consider the following:

```ts
const Rollup = ZkProgram({
  name: "rollup-example",
  publicInput: Field,

  methods: {
    oneStep: {
    privateInputs: [ Field, Field, Field, Field, Field, MerkleMapWitness ],

    method(
      state: RollupState,
      initialRoot: Field,
      latestRoot: Field,
      key: Field,
      currentValue: Field,
      incrementAmount: Field,
      merkleMapWitness: MerkleMapWitness
    ) {
      // ...
```

1. It's difficult to identify which element of `privateInputs` corresponds to which of the rest-spread parameters of `method`.
2. We should be able to infer the types of the rest-spread tuple from `privateInputs`.
3. We're unable to attach tsdocs to parameters. This would potentially be valuable for consumers of the program.

Ideally we could do the following.

```ts
const Rollup = ZkProgram({
  name: "rollup-example",
  publicInput: Field,

  methods: {
    oneStep: Method({
      /** some docs that are now attached to the `initialRoot` key */
      initialRoot: Field,
      latestRoot: Field,
      key: Field,
      currentValue: Field,
      incrementAmount: Field,
      merkleMapWitness: MerkleMapWitness,
    }, (state, { initialRoot, latestRoot, key, currentValue, incrementAmount, merkleMapWitness }) => {
      // ...
```

This also spares the developer of needing to––in their minds––shift the private inputs over by 1 (accommodating the public input).

**Comment by mitschabaude** [comment]
I agree with this proposal! Much more self-documenting. The required base type for method inputs could be `Record<string, Provable<any>>`

**Comment by mitschabaude** [comment]
would be awesome to combine this with https://github.com/o1-labs/o1js/issues/510 somehow
