### ISSUE TITLE
Polish and release local zkapp test runner

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#1732]
ideas copied from #1676:
* consider integration with node.js test runner
* support multiple contracts (the current version "natively" supports a single contract)
* ability to check for expected _on-chain_ states (currently you can only check offchain states and balances)
* in general better dogfooding: use it for more tests and see how it scales / what is missing
* think about a good name 😅

**Comment by mitschabaude** [comment]
a version of this is something we should add early on when designing the new API, so we have nice tests for new style SCs right from the start, and not this explosion of ugly tests we had for `SmartContract`

**Comment by Trivo25** [comment]
Good point; got this as part of https://github.com/o1-labs/o1js/issues/1677
