### ISSUE TITLE
[Prototype] Implement Blake Hashing for Mina Consensus Selection in o1js Circuit

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/o1js#1754]
LambdaClass needs to implement the Mina consensus selection algorithm in an o1js circuit. To achieve this, they require the Blake hashing function, which needs to be implemented as a gadget. We need to prototype this implementation and assess its feasibility, particularly focusing on performance and memory constraints.

**Objective:**

Prototype Blake hashing in o1js, evaluate its performance, and determine if it's suitable for use in the consensus selection algorithm implementation.

**Key Points to Address:**

1. Implement Blake hashing as a gadget in o1js.
1. Assess performance constraints, with a particular focus on memory usage.
1. Determine if the o1js implementation is feasible or if we need to switch to Snarky for native proving.

**Comment by Trivo25** [comment]
done
