### ISSUE TITLE
type safe UI worker interfaces

### ISSUE THREAD

**Issue by Trivo25** [o1-labs/o1js#1816]
make zkapp workers (UI) type safe, prevent nasty bugs when sending data across the UI

> allowing to pass native o1js types directly, type-safety on client side code, 'type-safety' when declaring zkappWorkerClient <-> zkappWorker interactions

see https://docs.minaprotocol.com/zkapps/tutorials/zkapp-ui-with-react

example https://github.com/KarolDevLtd/Sliced.club/blob/dev/client/src/pages/zkappWorker.ts

**Comment by mitschabaude** [comment]
or we just get rid of the need to run your own worker 😅

**Comment by ymekuria** [comment]
I agree with @mitschabaude here. I was always conflicted about adding examples of UIs with web workers as the recommended way of building UIs with o1js. In my opinion, web workers were always a temporary solution.
