### ISSUE TITLE
Export IndexedMerkleMapBase

### ISSUE THREAD

**Issue by dfstio** [o1-labs/o1js#1855]
**Proposal:**
Export IndexedMerkleMapBase. It is needed for the serialization of IndexedMerkleMap of any height. Now, only the function IndexedMerkleMap is exported, and I need to get this type using syntax like

```typescript
export function serializeIndexedMap(
  map: InstanceType<ReturnType<typeof IndexedMerkleMap>>
)
```
https://github.com/zkcloudworker/zkcloudworker-tests/blob/main/src/indexed-map.ts

**Comment by 45930** [comment]
Hey do you want to try to implement this yourself in a PR?  It sounds like you know what is required.  I think exporting that base type sounds ok.

**Comment by dfstio** [comment]
> Hey do you want to try to implement this yourself in a PR? It sounds like you know what is required. I think exporting that base type sounds ok.

Added https://github.com/o1-labs/o1js/pull/1856
