### ISSUE TITLE
assertOnCurve parameters

### ISSUE THREAD

**Issue by querolita** [o1-labs/o1js#1947]
While working on EdDSA I found something in the `assertOnCurve` used in ECDSA that looked fishy to me. 

```
function assertOnCurve(
  p: Point,
  { modulus: f, a, b }: { modulus: bigint; b: bigint; a: bigint }
) {
```

https://github.com/o1-labs/o1js/blob/ff64f93e049e775781873196214914aaaad85cf8/src/lib/provable/gadgets/elliptic-curve.ts#L171

Is that behavior expected? Meaning, that `a` gets mapped to `b` and `b` to `a`? Looks buggy to me 🤔

**Comment by mitschabaude** [comment]
the order doesn't matter in JS destructuring!

```ts
let { b, a } = { a: 0, b: 1 };
assert(b === 1); // works
```

and also, type annotations can never have any influence on the runtime behaviour in JS, because TS is just a syntax "add-on". so trying to deduce something about the runtime behaviour from a type is fundamentally a misunderstanding

**Comment by querolita** [comment]
Oh I had no idea! Thanks for the answer, I will close this issue then.
