### ISSUE TITLE
Use public output for account update returned from a zkApp method

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#275]
This is the snarkyjs equivalent of https://github.com/MinaProtocol/mina/issues/10747
So it's supported by Pickles, just needs to be used by snarkyjs.

**Comment by mitschabaude** [comment]
this is a required refactor if we don't want to run the prover method twice -- but I'm sure you will design it that way in zk processor

**Comment by Trivo25** [comment]
Will be part of the refactor!
