### ISSUE TITLE
"Cannot start new transaction within another transaction" after an attempt to produce txn using unknown to the network account

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/o1js#425]
#### Test Preconditions:
- `Account1` is known to the network (exists and pre-funded);
- `Account2` is not known by the network (no such account was created/imported).

#### Steps and Results:
- Deploy simple zkApp;
  - I've used this [one](https://github.com/o1-labs/e2e-state-zkapp/blob/develop/e2e-state-zkapp-sc/src/SquaredZkApp.ts)
- Then try to invoke `zkApp` method using `Account1` data as `owner's` or `feePayer's` PrivateKey, [example](https://github.com/o1-labs/e2e-state-zkapp/blob/develop/e2e-state-zkapp-ui/utils/ZkAppUtils.ts#L89)
  - All is good, txn created, proved, signed and sent.
-  Now try to invoke `zkApp` method using `Account2` data as `owner's` or `feePayer's` PrivateKey
    - You will get expected error like this:
      ```sh
      getAccount: Could not find account for public key B62qpH...
      ```
- After this point you will receive the following error message on any `zkApp` interaction attempt which involves txn creation:
  ```sh
  Error: Cannot start new transaction within another transaction
  ```

**Comment by mitschabaude** [comment]
thanks for creating this!! I'm sure it's missing a cleanup
