### ISSUE TITLE
Set `provedState` precondition by default

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#485]
This needs two things:
* ~~work on the ocaml side to make `isProved` available via grapjql~~ done
* tweak the default account update created by a zkApp so it has the isProved precondition set from the start. Note: this only applies for the account update which is created by a zkApp for itself. Maybe it's enough to modify `selfAccountUpdate()`

**Comment by es92** [comment]
Would propose this should be on any function besides an "init" one - that way devs avoid accidentally "blessing" a false state - eg a "powersOfTwo" contract with an `init` function that sets the state to `1`, but with a "double" method that doesn't check `isProved`, and so could take a non `isProved` state 3 to an `isProved` state 6
