### ISSUE TITLE
API to set the value of an existing variable

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#495]
I often am in the situation where I want to add constraints to a variable, which stay associated with the variable even if I change the value of it later. That's impossible now, because right now, "changing the value of a variable" -- for example, of one of the fields in an account update -- means assigning it to a different variable

**Comment by mimoo** [comment]
can you give an example of this? I'm not sure I understand : o

**Comment by mitschabaude** [comment]
@mimoo 
Ok, so preliminary situation is this: snarkyjs smart contract circuits are not written from top to bottom, in one function. Instead, they are a complex combination of stuff the user writes, stuff that gets added implicitly because of something the user writes, and stuff that gets added on top of all that inside a function which is wrapping the user code. It's spread out over many files and functions, and it's a complex machinery; I think the way the library is designed right now, it has to be that way.

Inside this complex circuit, there are a bunch of variables which are created at the beginning. They describe the Mina transaction that the smart contract creates & authorizes. It has stuff in it like the balance change for this user. For the sake of simplicity, let's just say I have a single `globalVariable`, which represents a variable + witness in the circuit.

Now I'm in the following situation: In some places in my library, I want to change the witness value of `globalVariable`. In other places, I want to add constraints to `globalVariable`, i.e. do something like `globalVariable.assertEquals(somethingElse)`.

However, there is currently no API (in snarkyjs at least) which allows me to change the witness value, without also _swapping out the variable itself_. Currently, I'm doing something like this when I want to change the witness value:
```ts
this.globalVariable = Circuit.witness(() => myNewWitnessValue);
```
The problem is that here, I'm replacing `globalVariable` with a new, completely unconstrained variable. I'm destroying any constraints I might have added before with something like `globalVariable.assertEquals(somethingElse)`.

**What I want is an API like this:**
```ts
this.globalVariable.setValue(() => myNewWitnessValue);
```

This would swap out the witness value that is currently assigned to this globalVariable, but without destroying all the constraints that are already on it

**Comment by mitschabaude** [comment]
Interesting, thx for the feedback @mrmr1993!

> reading any variable in an as_prover block could potentially fail or give a garbage value if you weren't careful

I _would_ have a default witness value for the variable though. In that sense, I'm not sure the asProver result would be "garbage"; it would just reflect the value before some other action was done which changed the value. Or maybe I'm missing some context about when asProver blocks are executed? If they're executed linearly as part of the circuit code, then it seems fine to me, on first glance.

**Comment by mitschabaude** [comment]
Btw, I do already have some patterns of "delaying constraints", but they all seem kind of ad-hoc and custom to me, where I define some custom enum to tell some other custom part of the code what constraints to add etc; a uniform API like setValue would solve the problem neatly

**Comment by mrmr1993** [comment]
> If they're executed linearly as part of the circuit code, then it seems fine to me, on first glance.

It's a pretty dangerous path to go down: all existing functions expect that the values are static, so if you do `let z = x.mul(y); x.setValue(() => blah)` then your witness will never be valid.

I started on an experiment with a separate 'delayed variable' kind, where it doesn't become a true variable until it gets filled, but I never finished it. If you're happy to have this kind of separation, we can probably make that work, although it'll take quite a lot of refactoring in the backend.

Presumably you could do the same entirely in SnarkyJS -- adding a variant of the field type with a 'delay' promise, and only adding the constraints after the promises for all variables in a constraint resolve -- since I imagine this is just for range checks on the preconditions?

**Comment by mitschabaude** [comment]
> It's a pretty dangerous path to go down: all existing functions expect that the values are static, so if you do let z = x.mul(y); x.setValue(() => blah) then your witness will never be valid.

Ok I see what you mean. It's not how snarky is designed right now -- `z`  won't get a different value if we change the `x` value after the fact. It won't work then I guess :)

> Presumably you could do the same entirely in SnarkyJS -- adding a variant of the field type with a 'delay' promise, and only adding the constraints after the promises for all variables in a constraint resolve -- since I imagine this is just for range checks on the preconditions?

This in interesting, I might explore that. I don't need it for range checks currently, What I most need it for right now is for the caller field, which is computed from a `isDelegateCall` Bool in the circuit, the value of which is changed in different places depending on if the zkApp has children / uses token APIs, and the value of which is constrained if a zkApp wants to assert that its child doesn't delegate authority
