### ISSUE TITLE
Remove Circuit class in favor of fast-path ZkProgram

### ISSUE THREAD

**Issue by bkase** [o1-labs/o1js#510]
We currently have 3 different interfaces for building zk proofs:
1. SmartContract
2. ZkProgram
3. Circuit

We ideally should have 1, but at least let's take one step closer towards 1 by moving to 2

ZkProgram is built on top of pickles so there's a slowness there, so to do this properly we should fast-path ZkProgram in the case where you don't need recursion to keep the performance

**Comment by bkase** [comment]
There's an additional thing that is not the same:

Circuit just has one entrypoint and ZkProgram has multiple entrypoints.

**Comment by TtheBC01** [comment]
Would be pretty nice to be able to bypass Pickles in ZkProgram when not needed. I've found up to 40% improvement on prove times between equivalent implementations between Circuits and ZkPrograms.

**Comment by Trivo25** [comment]
Agree! We were thinking about adding ZkFunction as an API for Kimchi. This could then be extended to support composability, where multiple ZkFunctions make up one ZkProgram

**Comment by TtheBC01** [comment]
Would this happen to be on the current o1js roadmap?

**Comment by mitschabaude** [comment]
obviously we should still do this, add `ZkFunction` but maybe that's tracked somewhere else

**Comment by Trivo25** [comment]
yep, will likely be part of the new API
