### ISSUE TITLE
APIs for real-time observing on-chain state (push, not pull)

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#531]

**Comment by bkase** [comment]
Some questions to think about for whoever spends time digging into this:

What’s the hotness with pushing these days? Websockets? What do web3js or other tools do for evented updates on txns? 

We’re pushing the onus on wallets and eventually backend indexing providers (at least until browser node). So whatever we should at least involve MinaExplorer and others in the discussion.

**Comment by mitschabaude** [comment]
@bkase maybe as a start, snarkyjs could do polling and just abstract it into a nice push API for developers.

as for the longer-term question, vanilla websockets work insanely well in my experience, they're easy to set up, reliable and fast

**Comment by Comdex** [comment]
Hey! Is the api that receives the events of the specified zkApp in real time also in the development plan? At the same time, a graphql subscription that can receive transactions under the specified receiving address in mempool in real time is also very useful.
