### ISSUE TITLE
CircuitString behaves inconsistently

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/o1js#541]
From @es92 
> Sometimes structures still behave oddly when declared on both a library and code using the library - CircuitStrings for instance will say they don’t type match with each other

Could you share any more detail please?

**Comment by es92** [comment]
When a CircuitValue is imported from an external npm library, it seems to initialize twice, and the version within the library and the imported are not compatible with each other. I observed this with CircuitStrings and MerkleWitnesses, but assume its a general CircuitValue thing
