### ISSUE TITLE
Use trick to get width 3 merkle trees

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#545]
...at almost no additional cost compared to binary Merkle trees, but allowing much more leaves!

As far as I understand, the trick works as follows:

For every pair of tree nodes `x`, `y` that are hashed, we add a third element `z` _to the hash_ to get the parent of `x`, `y`, `z`.

$$\mathrm{parent} = \mathrm{hash}(x, y) + z$$

**Comment by rpanic** [comment]
Possible attack scenario:
The adversary wants to prove an arbitrary `y'`. They could just calculate `h2 = hash(x, y')` and set the witness `z' = hash(x, y) - h2 + z`. 
With `x, y', z'` as the witness this would still compute the same root but with any chosen values for y. (This would also work for x, though not for z i think)

**Comment by mitschabaude** [comment]
Oh thanks for pointing that out @rpanic!

**Comment by rpanic** [comment]
I still think verkle trees are the way to go, though I still haven't found a commitment scheme which works well within snarkyjs
