### ISSUE TITLE
Add secp256k1 signature verification support

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/o1js#61]

**Comment by Comdex** [comment]
I'm interested in this feature. Also, it would be nice to add RSASSA-PKCS1-v1_5 signature verification and SHA256 hash support.
In this way, we can take advantage of the existing Internet infrastructure, such as the SubtleCrypto interface, which is widely supported by browsers, to manage the keys that can be used to control snapp. SubtleCrypto supports non-exportable keys to prevent the risk of disclosure of plaintext private keys.

**Comment by mitschabaude** [comment]
closed by #1307
