### ISSUE TITLE
Reduce SnarkyJS MB file size

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/o1js#610]
Creating an issue to track for the roadmap. Goal to make zkApp UIs more performant given SnarkyJS is is required to be loaded client side, it should be a reasonable KB/MB size.

To discuss and plan approach.

Targeted Q1 2023.

**Comment by stevenpack** [comment]
How big is the bundle now?

**Comment by mitschabaude** [comment]
> How big is the bundle now?

@stevenpack It's about 13MB iirc

**Comment by MartinMinkov** [comment]
https://bundlephobia.com/package/snarkyjs@0.9.5 
Just slightly less :D

**Comment by jasongitmail** [comment]
@stevenpack Worth mentioning that the primary cause is due to the JSOO (JS of Ocaml) library's code generation and related headaches and barriers to refactoring that it causes. Nonetheless, Product Eng team came up with ideas to help mitigate this in a material way during our team off site, which I'll document into a PRD.
