### ISSUE TITLE
Add keccak256 hash support

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/o1js#62]

**Comment by imengmengda** [comment]
Hello,  Jason. I'm interested in this feature.Moreover, I think it would be nice to add RSA signature verification to snarkyjs. But it's a bit difficult to implement it in existing libraries.

**Comment by jasongitmail** [comment]
Hi @imengmengda! Thanks for mentioning this. It'd be great to receive a PR for this or other functionality for SnarkyJS, if you're interested.

I discussed this with one of O1's cryptographic engineers for more details, and it sounds like this will be much easier to implement after APIs exist for lookups & range checks in both Kimchi and SnarkyJS. We don't have an estimate on when those may be available yet, but I'll update here when they're available or when we have more info.

**Comment by jasongitmail** [comment]
Update: O1's crypto team is adding Keccak256 to Kimchi. The SnarkyJS-related portion will be very easy, once it's done within Kimchi.

**Comment by xhliu** [comment]
Is it checked in yet? Also can u add `sha256` support?

**Comment by jasongitmail** [comment]
@xhliu Not yet. O(1) Labs' crypto team is working to add Keccak256 within Kimchi itself, for optimal performance. Currently they're prioritizing work for launching Berkeley Testnet and then will be able to focus on this. When Keccak256 is available within Kimchi, adding this method in SnarkyJS will be very quick.  They're also planning to add sha256 support within Kimchi, but that will be prioritized after Keccak256

**Comment by xhliu** [comment]
I can always code my own sha256 in Typescript using `snarkyjs`, right?
``ts
sha256(Field preimage): Field
``

It is just not as performant as adding it within Kimchi.

**Comment by xhliu** [comment]
BTW, what does this commit https://github.com/o1-labs/snarky/pull/489 do, regarding sha256?

**Comment by mitschabaude** [comment]
> BTW, what does this commit [o1-labs/snarky#489](https://github.com/o1-labs/snarky/pull/489) do, regarding sha256?

It's a 2 year old commit which deletes bindings to some C/libsnark code. We don't use libsnark anymore, and don't bind into C anymore. So I'd just ignore that commit, it's irrelevant to anything functionality we can offer now.

**Comment by Trivo25** [comment]
see https://github.com/o1-labs/o1js/issues/964
