### ISSUE TITLE
Local graphQL endpoint for UI development

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#623]
Raised by community member in discord

IS: When developing a UI, the current flow seems to be to deploy the smart contract to Berkeley, and interact via Auro with the deployed contract. This is an awful DX because developing the UI often goes hand in hand with developing / fixing the contract itself. The implied flow seems to be frequent redeployments / refunding, which can't be right.

SHOULD: It's easy to spin up an environment which simulates production, entirely locally. In particular, should include a local graphQL endpoint that Auro can talk with.

**Comment by bkase** [comment]
I think the easiest way to do this that’s guaranteed to be compatible with Mina is to create some new small ocaml executable that shares the graphql logic. A lot is functored already but we’d probably need to functor a little more to fully make it work. And/or add a flag to the main Mina binary that runs the graphql server but disconnects it from actually doing anything dangerous

**Comment by MartinMinkov** [comment]
Can we close this with Lightnet available now? :D

**Comment by ymekuria** [comment]
> Can we close this with Lightnet available now? :D

I think so @MartinMinkov unless anyone else thinks otherwise.

**Comment by mitschabaude** [comment]
Definitely!
