### ISSUE TITLE
Reliably catch compile/prove discrepancies

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#629]
Follow-up to #624
- Investigate why a discrepancy between compilation & proving caused an out of bounds error during the `compute_witness` in the Pickles wrap prover
- Exactly identify what in that bug was the underlying problem, and what the course of downstream effects, at a low level
- Find a way to identify this error earlier in the process, such that the error is more closely related to the cause
- Reliably communicate the underlying problem to the user

**Comment by mimoo** [comment]
Interesting, reading https://github.com/o1-labs/snarkyjs/issues/498 it seems like we're trying to access a witness value as part of `exists` (witness generation) or `as_prover` (debug). I think without better errors this will be hard to debug, so if this not urgent perhaps we can wait on getting better errors first

**Comment by mitschabaude** [comment]
This again cropped up as an important issues as several zkApp testers ran into these kinds of issues and they proved to be extremely hard to debug. A simple first step would be to reliably tell the user if there is a compile / prover discrepancy. It seems to do that we'd need to create a constraint system in the prover and return its digest, in a way that it can be used if the proof fails to identify this as a problem
