### ISSUE TITLE
Integrate DynamicArray

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#633]
There's a working, very high quality dynamic array implementation from the builder's program: https://github.com/gretzke/zkApp-data-types

We should add it to snarkyjs!

**Comment by jasongitmail** [comment]
@mitschabaude What are the limitations or differences between this solution vs one built when the underlying proof system supports extended lookup tables (currently in Kimchi, but not yet in Pickles, as of today)?

**Comment by mitschabaude** [comment]
> @mitschabaude What are the limitations or differences between this solution vs one built when the underlying proof system supports extended lookup tables (currently in Kimchi, but not yet in Pickles, as of today)?

I think this solution already has the final API, so implements what we want feature-wise. The future version with proof system support would then make some of the operations much more efficient.

For example, an array lookup currently creates `O(N)` constraints, where `N` is the static max array size. In the future, it should be `O(1)` (actually, close to 1) constraints.

Note, I don't think we can avoid the static max size, even with extended lookup tables. (Same for strings.) I'm also not sure if all of the basic operations can be brought down from `O(N)`.

**Comment by Trivo25** [comment]
see #90 #1062
