### ISSUE TITLE
Get rid of decorators

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#670]
Probably means getting rid of the SmartContract class

**Comment by maht0rz** [comment]
Is there a new proposed API as this sounds like `@method` or `@state` are going away? I'm asking since we're designing a new library to extend snarkyjs and want to make sure our API design wont become obsolete.

**Comment by mitschabaude** [comment]
It's still TBD if we even want to act on this issue, but the only replacement candidate for decorators that I'm aware of is the API we have for ZkProgram, where `method` and `privateInputs` are separate keys to an object which described the circuit
