### ISSUE TITLE
Improve error seen by dev when invalid_fees_excess occurs

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/o1js#684]
We've had a couple user reports of a confusing error message when transaction fee is insufficient. E.g.

> Error due to the cost when deploying a smart contract to testnet aren't really helpful to tell me what to fix when it happen. ( ex: invalid_fees_excess ? where ? what to fix ? no idea, but I eventually found something )

Any ideas why this is occurring? Is the fee calculation method incorrect? Once the SnarkyJS side is improved, we should discuss how to better expose this via the zkApp CLI too.

**Comment by MartinMinkov** [comment]
We have https://github.com/o1-labs/o1js/blob/24537f740f82c2922a61e937b28fae8bf0fe068c/src/lib/mina/errors.ts#L8, closing this out
