### ISSUE TITLE
Literal BigInt is not supported on react-native

### ISSUE THREAD

**Issue by chezhe** [o1-labs/o1js#707]
Literal BigInt is not supported on react-native, better get rid of them like Aptos https://github.com/aptos-labs/aptos-core/pull/3943

**Comment by mitschabaude** [comment]
I think bigint literals are important. If this was the thing preventing snarkyjs to work in RN, then I'd look into transpiling the literals away; possibly on the RN build pipeline and not here.

However, AFAIK, Wasm and web workers are not supported in React native, which prevents any chance for snarkyjs running in RN, so this doesn't seem relevant right now?

**Comment by chezhe** [comment]
For me, mina-signer package contains BigInt literals and cannot be compiled on react-native. If BigInt(0) is same with 0n, and it can runs on more platforms, it will be a better choice in coding.

Or maybe the BigInt literals can be transformed with babel after build.

**Comment by mitschabaude** [comment]
That's a great point @chezhe. We want mina-signer to be compatible with RN. Yeah maybe you can try to transform them with babel or another tool in your build

**Comment by chezhe** [comment]
I try to transform all BigInt literals into BigInt(n), but I don't know how to transform 
type Bool = 0n | 1n

**Comment by mitschabaude** [comment]
Cool! You could transform `0n | 1n` to `bigint`
