### ISSUE TITLE
extending a smart contract causes state to access the same values 

### ISSUE THREAD

**Issue by Trivo25** [o1-labs/o1js#768]
@maht0rz ran into the following problem:

Extending smart contract causes state to access the same value (index in the state array), if the contract that is being extended already has state

```ts

class A extends SmartContract {
	@state(Field) a1 = State<Field>();
}

class B extends A {
	@state(Field) a2 = State<Field>();
	@state(Field) b2 = State<Field>();
}

```  

In this case, `a1` and `a2` will access and modify the same value

**Comment by mitschabaude** [comment]
There are a couple of other things that I believe don't work when extending. E.g. decorated methods on the base contract are not available for proving. It's completely broken

**Comment by maht0rz** [comment]
Would be great to see support for all the decorators in extende classes 👍
