### ISSUE TITLE
Improve UX of setting timing & permissions

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#770]
There are two account fields which are a bit annoying to set, because they are big objects of many properties, all of which need to be set at once; but the developer might only care about setting a few of the properties.

We should go for a DX where the developer only has to specify a subset of values:
```ts
this.account.permission.set({ editState: Permissions.proofOrSignature() });
this.account.timing.set({ initialMinimumBalance: x, cliffAmount: x, cliffPeriod: y });
```

TBD: what to use as default values. I think

* Permissions should use existing permissions as backdrop default (but need to handle cleverly in `deploy()` to not override the setting of `Permissions.default()` with user-defined permission setting
* Timing should just use fixed default values. There would be some restriction -- initial minimum balance can't be left out, and either `cliffAmount` + `cliffTime`, or `vestingIncrement` should be provided, to avoid a setting where the tokens can never unlock

Related DX improvement: Snarkyjs should fail early if `timing.vestingPeriod` is set to `0`, because the protocol doesn't allow that

**Comment by jasongitmail** [comment]
For context where this came up in docs review: https://github.com/o1-labs/docs2/pull/276#discussion_r1121792532
