### ISSUE TITLE
Provide an interface to specify absolute cliff time as dates, and fix docs

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/o1js#821]
Time locked accounts currently don't work [as documented](https://docs.minaprotocol.com/zkapps/advanced-snarkyjs/time-locked-accounts), because the docs assume cliff time is set relative to the transaction which sets timing, while in reality it seems to be interpreted as an absolute slot number (of the slot at which the cliff time is over).

We should either fix the docs or (my suggestion) make the interface in snarkyjs treat the cliff time as a relative slot number, because that will be most certainly easier to use.

EDIT: plan changed, see below

**Comment by mitschabaude** [comment]
Instead of the above, we decided to keep the absolute time and provide an interface for converting times / dates into global slots

**Comment by barriebyron** [comment]
@mitschabaude I opened PR https://github.com/o1-labs/docs2/pull/355 for updates to the the https://docs.minaprotocol.com/zkapps/advanced-snarkyjs/time-locked-accounts page

I have to learn how to bring in that updated graphic.

Can you use this PR for your changes? Teach me if there is a better way to work this. Thank yoU!

**Comment by mitschabaude** [comment]
> Can you use this PR for your changes? Teach me if there is a better way to work this. Thank yoU!

Yes that works 👍🏻
