### ISSUE TITLE
Dynamic array access

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/o1js#90]

**Comment by mitschabaude** [comment]
Depends on implementation of extended lookup tables: https://github.com/o1-labs/proof-systems/pull/250

**Comment by jasongitmail** [comment]
Relate:, see https://github.com/o1-labs/snarkyjs/issues/633 from ZBP2, but note that it was built at a time when extended lookup tables were not available in the underlying proof system.

**Comment by joseandro** [comment]
@mitschabaude can we close this one?

**Comment by mitschabaude** [comment]
> @mitschabaude can we close this one?

@joseandro we haven't integrated runtime tables in o1js yet so it's not done. But I think it can be closed for redundancy with https://github.com/o1-labs/o1js/issues/1086

**Comment by Trivo25** [comment]
closing because redundant; pointing to #1086
