### ISSUE TITLE
Warning or error for `AccountUpdate` in ordinary conditional

### ISSUE THREAD

**Issue by Isaac-DeFrain** [o1-labs/o1js#904]
I noticed that if one does something like
```typescript
if (someCondition) {
  this.send({ to, amount })
}
```
inside of a smart contract method, then even when `someCondition` evaluates to `true`, the account update not only does not happen, but no warning or error is provided. Something along the lines of notifying the dev that they did an account update inside an ordinary conditional, but need to do this inside of a `Circuit.if` for it to take effect would be very helpful.

**Comment by mitschabaude** [comment]
That behavior doesn't seem plausible to me. If `someCondition` is always a truthy JS value, then that conditional will always be executed. This is how JS works and has nothing to do with snarkyjs
