### ISSUE TITLE
Turn proving off by default

### ISSUE THREAD

**Issue by nicc** [o1-labs/o1js#922]
To speed up the development workflow
Proving should be turned off by default

Questions:
- Does this open up the potential to deploy broken apps? Would a dev miss catching any issues if proofs aren't generated until the app is deployed?
- What needs to change in our documentation and tutorials?

**Comment by mitschabaude** [comment]
I see some risks in doing this. One change that we should definitely make alongside this is to run the transaction callback in "checked computation mode", i.e. using `runAndCheck`. This will catch basic stuff that you can't do in a circuit, like reading out field element values.

Still, there's a large error surface, including writing circuits that change each time you run them, which is not captured when running with proofs disabled. It would be nice if we could reduce that error surface over time and add more checks that emulate the full prover environment without incurring the costs of proving

**Comment by mitschabaude** [comment]
We're talking about LocalBlockchain

**Comment by Trivo25** [comment]
We now have a flag for this in `LocalBlockchain`, i think we can consider this done?
