### ISSUE TITLE
Create a single Benchmark of a core development workflow

### ISSUE THREAD

**Issue by nicc** [o1-labs/o1js#923]
In order to improve developer and user experience through faster workflows
All core components in the critical path should be benchmarked for a baseline and ongoing comparison

This issue is to create the **first** benchmark.
Some options:
- Compilation
- Proof generation
- (SnarkyJS) Verification
- Startup time
- Deployment
- ...anything else? Scaffolding is infrequent and interactive so is it worth measuring?

Benchmarks should be derived from CI or nightly builds (as opposed to user telemetry) and published somewhere. 
Benchmarks should have reliable output (at the software level) that can be interpreted statistically

**Comment by shimkiv** [comment]
- View/rendering example of ["publish somewhere"](https://o1labs-grafana.p42.xyz/d/H-L-ytP4k/snarkyjs-simple-benchmarking?orgId=1&refresh=10s&from=now-30d&to=now).

> Should we warn on performance regression?

Definitely but baseline should be established first.

> How do we systematise / get into the habit of checking performance impacts and communicating them with every release?

As part of PR gates/chaecks?

**Comment by garwalsh** [comment]
Related RFC:
https://app.zenhub.com/workspaces/sdk-6130fedb3b0fc600123d8796/issues/gh/o1-labs/rfcs/28
https://github.com/o1-labs/rfcs/pull/28/files

**Comment by garwalsh** [comment]
Let's also scope the work to include some of the benchmarks here: https://zkbench.dev/
We could use some of the tests here to derive our own internal metrics at the same time.

At a minimum, we should be benchmarking our native primitives ECDSA, Keccak, SHA256 (eventually RSA, Groth16 etc)
