### ISSUE TITLE
(Feature request) Easier way to increment nonce

### ISSUE THREAD

**Issue by Isaac-DeFrain** [o1-labs/o1js#941]
It would be very nice to have an easier way to increment an account's nonce. I see at least three ways to do it:
- change the type of the `nonce` field in `FeePayerSpec` to `UInt32` (it is `UInt32` in `Account` after all)
- add a method to `UInt32` to convert to `number`
- add an `incrementNonce()` method to `Account` (or something along those lines)

**Comment by mitschabaude** [comment]
Thanks! Both of the first two sound very helpful! So I'm guessing you want to optimize a code snippet that
* gets /fetches an account
* take the nonce from there
* pass this nonce + 1 to the fee payer spec

**Comment by mitschabaude** [comment]
FWIW, I think an important change is to fetch an account's nonce from the tx pool instead of from the last block (there is a graphql query for that)

**Comment by Isaac-DeFrain** [comment]
> gets /fetches an account
take the nonce from there
pass this nonce + 1 to the fee payer spec

That's exactly my use case! The simplest way I could find to do it in the current state is this

```typescript
function wellDefine(n: UInt32 | undefined) {
  if (n === undefined) {
    return UInt32.zero;
  } else {
    return n;
  }
}

// new nonce
let nonce = 0;
while (
  UInt32.from(nonce)
    .lessThanOrEqual(wellDefine(feePayerAccount?.nonce))
    .toBoolean()
) {
  nonce += 1;
}
```

**Comment by Isaac-DeFrain** [comment]
> FWIW, I think an important change is to fetch an account's nonce from the tx pool instead of from the last block (there is a graphql query for that)

Agreed. Fetching the nonce from the last block doesn't necessarily prevent the `Insufficient_replace_fee` errors. My hope is that having an easy way to increment nonces will do just that.
