### ISSUE TITLE
`getNetworkState` doesn't fetch network state

### ISSUE THREAD

**Issue by Isaac-DeFrain** [o1-labs/o1js#944]
Neither the Mina Explorer or Minascan GraphQL endpoints return the network state via `Mina.getNetworkState()`

![image](https://github.com/o1-labs/snarkyjs/assets/42081488/f8f9fd7e-a122-4098-a142-d5ed18fc607b)
![image](https://github.com/o1-labs/snarkyjs/assets/42081488/4ccd45f9-78b8-40ee-8a76-974b52879035)

**Comment by mitschabaude** [comment]
the API is probably misleading. this is for getting a cached network state inside `MIna.transaction` (where async fetches are not possible). To fetch the network state, there is the top level export `fetchLastBlock()`

**Comment by Isaac-DeFrain** [comment]
That certainly explains why `getNetworkState()` is not async.

**Comment by Isaac-DeFrain** [comment]
Some additional comments for that method could clear up this confusion
