### ISSUE TITLE
Action/Event limits LocalBlockchain vs Berkeley

### ISSUE THREAD

**Issue by Isaac-DeFrain** [o1-labs/o1js#947]
Up to 100 actions/events are supported per transaction on `Mina.LocalBlockchain()` but only up to 16 are supported on the Berkeley network. As a result, one could pass all tests locally and still deploy an incorrect contract.

**Comment by shimkiv** [comment]
Thanks! We're aware of this issue, the [limits](https://github.com/o1-labs/snarkyjs/blob/f250e614eb7ff62741210db037d29a8ac710e60f/src/lib/mina/constants.ts#L25) you mentioned are applied across whole the SDK, not only for LocalBlockchain. Next Berkeley redeployment will match limits.
