### ISSUE TITLE
(Feature request) Cache contract compilation artifacts

### ISSUE THREAD

**Issue by Isaac-DeFrain** [o1-labs/o1js#951]
Every time you run a script to interact with a smart contract, you have to first compile the contract which takes a significant amount of time (~30-45 sec). It would be really nice if the provers, verification key, and verify function were cached on the first compilation to speed up future interactions with the same contract!

**Comment by ycryptx** [comment]
I'm building a system that uses a MapReduce to speed up proof accumulation. The ZKProgram compilation happens on every run of the MapReduce operation, and thus degrades the performance improvements I'm trying to get with parallelizing the proving. Without being able to precompile the program, developers like me would find it difficult to accelerate the proving time of contracts

**Comment by nicc** [comment]
+100 for this in a local context. I also think it's worth thinking about this compilation time in a production / deployed-to-web context. I believe the compiled artefacts can be very large so we probably can't just generate and deploy them to prod. Too big a payload size. But are there smaller, intermediate artefacts that can be added to a web payload to speed of compilation for end users?

I don't think this issue should contain this scope btw. We should just consider it when designing a solution.

**Comment by mitschabaude** [comment]
Done!

**Comment by ycryptx** [comment]
@mitschabaude How do I 'load' a compiled contract? What I'm trying to do is compile it once and then start a bunch of containers with the compiled Zkapp.
