### ISSUE TITLE
Provide a clear API for verifiying ECDSA signatures, based on exposed primitives

### ISSUE THREAD

**Issue by nicc** [o1-labs/o1js#968]
Here's a circuit built with Circom that needs to verify an ECDSA signature for reference: https://github.com/BigWhaleLabs/seal-hub-ecdsa-verifier-contract/blob/main/circuits/ECDSAChecker.circom

Provide a clear, easy-to-use interface for performing this kind of operation. Do we need to wrap the primitives exposed previously in this epic?

**Comment by nicc** [comment]
This should start alongside #970 to parallelise and share context.

**Comment by mitschabaude** [comment]
TODO: fix TS output of inline classes like `ForeignField`, `ForeignCurve`. It seems we need to define an abstract class or something to make this work
