### ISSUE TITLE
Benchmark ECDSA signature verification relative to Circom

### ISSUE THREAD

**Issue by nicc** [o1-labs/o1js#969]
Reference implementation: https://github.com/BigWhaleLabs/seal-hub-ecdsa-verifier-contract/blob/main/circuits/ECDSAChecker.circom

How does our performance compare to Circom for the same action above?

Measure all key stages of the developer journey:
- Compilation
- Proof generation
- Verification

This work should be repeatable, even if it's not integrated. i.e. we should be able to build on this or at least integrate it into further becnhmarking efforts. Basically, we don't want to waste this effort by doing a one-off thing, but we also don't want to block benchmarking results until we have an entire framework.

**Comment by stevenpack** [comment]
@barriebyron can you watch this issue? good be a good blog post opportunity

**Comment by Trivo25** [comment]
status: running the ECDSA circom verifier takes 12s for witness generation and 8s for proving (20s total) on my PC -- will follow up with the repo and other hardware once proving of ECDSA works in SnarkyJS
