### ISSUE TITLE
Document ECDSA signature verification

### ISSUE THREAD

**Issue by nicc** [o1-labs/o1js#970]
Create a tutorial that steps through ECDSA signature verification. It shouod be based on the API defined in [this issue](https://github.com/o1-labs/snarkyjs/issues/968).

See reference implementation using Circom: https://github.com/BigWhaleLabs/seal-hub-ecdsa-verifier-contract/blob/main/circuits/ECDSAChecker.circom

From Phil:
ECDSA is the elliptical cryptography scheme used by Ethereum.  SnarkyJS can’t “read” things from Ethereum without having a custom gate for ECDSA. After we have ECDSA, SnarkyJS can allow people eg, to attest to the fact that they own a bored ape on Ethereum without doxxing themselves, or that they have an ETH balance of more than x.  There may also be use cases outside Ethereum

**Comment by barriebyron** [comment]
I've circled in with Phil Kelly to find out what a use case looks like. Who is the partner for the code in the tutorial?

@nicc  who will be responsible for delivering the example code for https://github.com/o1-labs/docs2/tree/main/examples/zkapps ? 

I am up for working on the content but do require engineering support for the command sequence and code

ill we have an example in

**Comment by barriebyron** [comment]
@Trivo25  thank you for being the example code hero!

**Comment by nicc** [comment]
This should start alongside #968 to parallelise and share context.

**Comment by barriebyron** [comment]
SnarkyJS PRs can merge only after crypto updates are in:
https://github.com/o1-labs/snarkyjs/pull/999
https://github.com/o1-labs/snarkyjs/pull/989
https://github.com/o1-labs/snarkyjs/pull/988

**Comment by barriebyron** [comment]
SnarkyJS PRs can merge only after crypto updates are in:
https://github.com/o1-labs/snarkyjs/pull/999
https://github.com/o1-labs/snarkyjs/pull/989
https://github.com/o1-labs/snarkyjs/pull/988

**Comment by barriebyron** [comment]
Doc outlined in draft PR https://github.com/o1-labs/docs2/pull/562 and ready for dev contributions from @MartinMinkov  or @Trivo25

**Comment by barriebyron** [comment]
@nicc I expected to find this issue in the https://github.com/o1-labs/docs2 repo... I don't see how to transfer it, as the author, are you able to move it? 
I successfully moved an issue recently... maybe because I was the author? Can you try to move to the docs2 repo?
