### ISSUE TITLE
Document eng. workflow using a local network in Docker 

### ISSUE THREAD

**Issue by nicc** [o1-labs/o1js#981]
In order to test against a real network (more easily)
As an **internal** code contributor
I want instructions on running a local network in Docker

**Acceptance Criteria**
When I clone the SnarkyJS repo
Then I can see instructions on running a local network in Docker in the **developer** (not public / homepage) [README-DEV](https://github.com/o1-labs/snarkyjs/blob/main/README-dev.md)
And those instructions work when I follow them

**Comment by mitschabaude** [comment]
can we change `README` to `README-dev`?

**Comment by barriebyron** [comment]
I wrote this doc for another project I worked on https://docs.ignite.com/guide/docker
